package google;

public class ListMovies {
	
	/*public final static String NAMES[] = {"Força de Viver",
			"O Casamento Dos Meus Sonhos",
			"O Amor De Um Pai",
			"O Misterio Da Libelula",
			"Por Favor, Matem Minha Mulher",
			"10 Horas Para o Natal "};*/
	
	public final static String NAMES[] = {"Força de Viver",
			"O Casamento Dos Meus Sonhos",
			"O Amor De Um Pai",
			"O Misterio Da Libelula",
			"Por Favor, Matem Minha Mulher",
			"10 Horas Para o Natal ",
			"Interludio De Amor",
			"A Maldiçao Da Pantera-Cor-De-Rosa",
			"Mister Brau: O Filme ",
			"Kung Fu Panda 2",
			"Megan Leavey ",
			"Spymate: O Agente Animal",
			"Beethoven, O Magnifico",
			"Meus Vizinhos Sao Um Terror",
			"Memorias Secretas",
			"A Ilha Do Dr. Moreau",
			"Panico Na Torre",
			"Pai E Filho",
			"A Valsa Do Imperador",
			"Uma Temporada Brilhante",
			"Aparecida: O Milagre",
			"O Hospede Quer Bananas",
			"Jogada De Mestre 2: Totalmente Radical",
			"A Vida e Bela",
			"Papai Noel Trapalhao",
			"Viagem Ao Fundo Do Mar",
			"Sonhos de Papel",
			"Todo Poderoso",
			"Dirty Dancing: Ritmo Quente",
			"O Jovem Ivanhoe",
			"O Leao",
			"Um Homem e sua Alma",
			"Meu Pequeno Ladrao",
			"Corretores Do Amor",
			"Meteoro",
			"Sob A Mesma Lua",
			"The Cheetah Girls: Um Mundo",
			"Maquina Mortifera 2",
			"Os Donos Da Noite (1989)",
			"Minha Namorada Favorita",
			"Meu Melhor Amigo",
			"Madre Tereza: Em Nome dos Pobres de Deus",
			"Por Amor de Benji",
			"Ainda uma vez com Emoçao",
			"Zorro Contra o Imperio da Espada ",
			"Ace: Uma Questao De Justiça",
			"Quando O Amor Acontece",
			"O Voo Do Navegador",
			"Feitiço Do Tempo",
			"O Amor Nao Vai A Guerra",
			"Papai Batuta",
			"Errado Pra Cachorro",
			"As Garotas Do Escritorio",
			"Minha Querida Brigitte",
			"As Aventuras de Mario Fofoca",
			"Farra no Gelo ",
			"O Bom Filho a Casa Torna",
			"Abracadabra",
			"O Cangaceiro Trapalhao",
			"Negocios De Familia",
			"Uma Aventura Animal (2013) ",
			"Quero Ser Grande",
			"Espiao Por Engano",
			"aguia De Aço",
			"A Volta De Roxy Carmichael",
			"O Resgate (1988)",
			"A Noviça Rebelde",
			"Miami Vice (1984)",
			"O Capitao Pirata",
			"Ferias de Amor ",
			"A Viagem do Yes ",
			"Shrek 2",
			"O Besouro Verde",
			"Porta Do Ceu",
			"Leis Da Atraçao",
			"O Guardiao 2: O Retorno Das Minas Do Rei Salomao",
			"O Milagre Veio Disfarçado",
			"Romance Moderno",
			"Os Tres Mosqueteiros (1974)",
			"O Bom Gigante Amigo ",
			"Os Caça-Fantasmas (1984)",
			"Uma Aventura do Zico",
			"O Pe Grande: O Encontro Inesquecivel",
			"Frente A Frente",
			"Natal Em Julho",
			"A Herança De Mr. Deeds",
			"Arrebentando Em Nova York",
			"Caravana Da Coragem",
			"O Mundo Fabuloso Do Circo",
			"Impacto Fulminante",
			"As Neves Do Kilimanjaro",
			"A Torre Do Terror",
			"Cocoon",
			"O Milagre Veio Do Espaço",
			"Hudson Hawk: O Falcao Esta a Solta",
			"Peggy Sue, Seu Passado A Espera",
			"Apertem Os Cintos... O Piloto Sumiu",
			"Uma Historia Natalina",
			"Cinderela em Paris ",
			"Bee Movie: A Historia De Uma Abelha",
			"Lancelot, O Primeiro Cavaleiro",
			"Zenon: A Corrida Para A Lua",
			"A Incrivel Jornada 2: Perdidos Em Sao Francisco",
			"Nos Sempre O Amaremos",
			"O Feitiço Da Lua",
			"O Mundo Em Seus Braços",
			"Elvis Triunfal",
			"indios",
			"Aventuras De Um Cachorro",
			"O Passaro Azul (1940)",
			"Voando Para O Alem",
			"Topper e o Casal do Outro Mundo",
			"A Fera",
			"Top Gun: Ases Indomaveis",
			"Gracie",
			"O Homem Do Sapato Vermelho",
			"O Leao Esta Solto ",
			"Minha Amiga Ficka ",
			"Divino Processo",
			"O Cachorro Bombeiro",
			"Segurem Essas Crianças",
			"Inimigo Meu",
			"Saudades De Um Pracinha",
			"Sonhando de Olhos Abertos",
			"O Impossivel ",
			"Ta Chovendo Hamburguer",
			"Turbo",
			"Sequestro Por Engano",
			"O Guardiao: Em Busca Da Lança Sagrada",
			"Joey, Um Canguru em Apuros",
			"Gasparzinho: O Fantasma Camarada",
			"O Corcel Negro",
			"A Volta Do Grande Monstro",
			"Mustang Selvagem",
			"Quando Eu Te Amei",
			"Caofusoes",
			"Quebrando O Gelo",
			"A Incrivel Jornada",
			"O Resgate De Laura Mahone",
			"O Golpe Perfeito",
			"Crown, O Magnifico",
			"Oh! Que Delicia De Guerra",
			"Como Agarrar um Milionario",
			"Atraçao Explosiva",
			"The Super: O Dono Do Pedaço",
			"As Loucas Aventuras De Uma Familia Americana Na Europa",
			"A Garotinha Que Caiu Do Ceu",
			"Os Garotos Perdidos",
			"Digam O Que Quiserem",
			"Agarre-Me Se Puderes",
			"Dama De Ouro",
			"Rochedos da Morte",
			"O rei Vagabundo",
			"Escola de Serelas",
			"Meu Pe De Laranja Lima (2012) ",
			"Meu Filho Das Selvas",
			"Mong & Loide",
			"Vivendo Com Estilo",
			"Marcados Pela Guerra",
			"Ladrao Por Excelencia",
			"Amor De Milionario",
			"Meu Tio Matou Um Cara",
			"Ele Disse, Ela Disse",
			"O Menino E A Onça",
			"Um Biruta em orbita ",
			"Voando Alto (2003)",
			"Bebes Geniais 2: Super Bebes",
			"Robin Hood: O Heroi Dos Ladroes",
			"Casey, Toby E Gil",
			"Vibes: Boas Vibraçoes",
			"A Inveja Mata",
			"Napoleon: As Aventuras De Um Caozinho Valente",
			"A Morte Do Incrivel Hulk",
			"Meu Adoravel Androide",
			"O Bamba do Regimento ",
			"Um Tio Quase Perfeito",
			"a Procura da Felicidade",
			"Police Story: A Guerra Das Drogas",
			"Rocky 2: A Revanche",
			"Melrose",
			"E O Ceu Continua Esperando...",
			"O Mundo Perdido",
			"Festa Brava ",
			"As Regras De Max",
			"Uma Escola Muito Louca",
			"A Mascara do Vingador",
			"Festa no Gelo ",
			"Divorcio ",
			"A Origem Dos Guardioes",
			"Aladdin (1992)",
			"O Cachorro Bionico",
			"Aprontando Em Alto-Mar",
			"Loucuras Do Coraçao",
			"Fuga a Meia-Noite",
			"Melodia Interrompida",
			"Palavras do Coraçao ",
			"Andy Hardy Banca o Xerloque ",
			"Joy: O Nome do Sucesso",
			"A Luta Por Um Ideal (2012)",
			"Os Trapalhoes No Reino Da Fantasia",
			"Barrabas",
			"Entrando Numa Fria Maior Ainda",
			"O Mar Nao Esta Pra Peixe",
			"Voo De Fantasia",
			"O Casamento De Betsy",
			"Kelly E Eu",
			"O Disco-Voador",
			"Ilha Da Aventura",
			"O Grande Mentiroso",
			"Um Agente Muito Secreto",
			"Um Amor No Fim Do Ano",
			"Condorman, O Homem Passaro",
			"Situaçao Critica",
			"O Melhor Amigo da Noiva",
			"O Diario de Uma Baba",
			"Resgate Do Amor",
			"Volcano: A Furia",
			"A Cidadela Dos Robinsons",
			"Uma Janela Para O Ceu 2",
			"Livres Como O Vento",
			"Milionario Num Instante",
			"Scooby-Doo E Os Irmaos Pavor",
			"Amor Entre Ladroes",
			"Um Favor Muito Especial",
			"O Escudo Negro De Falworth",
			"No Compasso da Esperança",
			"Loucas Por Amor, Viciadas em Dinheiro ",
			"Castelo Ra-Tim-Bum: O Filme",
			"O Clube Das Desquitadas",
			"Blue De Ville: O Cadillac Azul",
			"Quando Papai Noel Salvou O Natal",
			"Seaquest: Missao Submarina",
			"A Vida Secreta De John Chapman",
			"Louuras de um Milionario",
			"De Caniço e Sambura ",
			"A Feiticeira (2005)",
			"Maldito Feliz Natal ",
			"Voltando a Sonhar",
			"Zona De Perigo",
			"Uma Noite De Aventuras",
			"A Outra Historia Do Profeta",
			"Tammy E O Milionario",
			"Oito Homens de Ferro ",
			"Gasparzinho, Como Tudo Começou",
			"O Tempo Do Lobo",
			"A Invasao",
			"Os Nerds Saem Em Ferias",
			"Mamae Nota 10",
			"Highlander, O Guerreiro Imortal",
			"Jogo De Defesa",
			"O Natal Magico",
			"Problemas Em Dobro",
			"Maridos Em Ferias",
			"O Segredo De Uma Promessa",
			"A Princesa E O Motorista",
			"O Grande Desafio",
			"Ninguem Segura Esses Fantasmas",
			"Um Mundo Que Mudou",
			"Boa Viagem, Charlie Brown",
			"Circo Dos Fantoches",
			"Sully: O Heroi do Rio Hudson",
			"Truque de Mestre",
			"Aventura dos Sete Mares",
			"Homem-Aranha 3 ",
			"Os Sem-Floresta",
			"Um Namorado De Aluguel",
			"Sou Ou Nao Sou",
			"O Agente Flintstone 1007 A.C. ",
			"Poderoso Joe (1998)",
			"Procurando Por Lola",
			"Hercules No Labirinto Do Minotauro",
			"Loucademia De Policia 2: Primeira Missao",
			"Crocodilo Dundee",
			"Love Story: Uma Historia De Amor",
			"Rio 2",
			"De Justin Para Kelly",
			"A Espada Era A Lei (1963) ",
			"Contatos Imediatos De 3º Grau",
			"Os Quatro Picaretas",
			"Solteiras a Solta ",
			"Namoro Virtual",
			"Pode-me Chamar De Noel",
			"Porkys Contra-Ataca",
			"De Volta Para O Futuro 2",
			"Furia Vermelha",
			"Clube Dos Pilantras 2",
			"A Seta De Ouro",
			"Piratas Pirados! ",
			"Quando em Roma",
			"Mulan 2: A Lenda Continua",
			"Ruas De Fogo",
			"De Repente Gravida",
			"Flashdance, Em Ritmo De Embalo",
			"Meu Pai, Eterno Amigo",
			"A Chama de Calcuta",
			"A Mulher do Seculo",
			"Casanova",
			"O Menino Magico ",
			"Volta Ao Mundo Em 80 Dias: Uma Aposta Muito Louca",
			"Um Amor De Estimaçao",
			"American Ninja 5",
			"As Tartarugas Ninjas 3",
			"O Gorila ",
			"Quanto Mais Musculos, Melhor ",
			"As Branquelas",
			"Twitches: As Bruxinhas Gemeas 2",
			"Barbie Em O Quebra Nozes",
			"Cara De Um, Focinho De Outro",
			"A Montanha Enfeitiçada (1975)",
			"Resgate Suicida",
			"A Lenda De Longwood",
			"Xuxa Abracadabra",
			"As Tartarugas Ninja 3",
			"Um Trapaceiro Genial",
			"Poçao Do Amor Nº9",
			"Super Force",
			"Quem Esta Guardando Essa Erva? ",
			"Jogada De Mestre",
			"Aluga-se Um Garoto",
			"Regresso Ao Mundo Maravilhoso De Oz",
			"Os Perigos De Paulina",
			"3 Ninjas Contra-Atacam",
			"Bud 3: Jogando Futebol",
			"Lua De Cristal",
			"3 Ninjas",
			"Alta Ansiedade",
			"O Pior Calhambeque Do Mundo",
			"O Tesouro de Tarzan ",
			"Velocidade Maxima 2",
			"Dr. Dolittle 3",
			"Fuga Mortal",
			"O Circo Ao Redor Do Mundo",
			"Viagem Rumo ao Infinito",
			"Robin Hood, o Invencivel ",
			"a Primeira Vista",
			"Um Ratinho Encrequeiro",
			"O Demonio Na Garrafa",
			"Carrasco do mar",
			"Lembranças do ultimo Natal ",
			"Wall-E",
			"Afinado No Amor",
			"Super Colosso",
			"A Grande Barbada",
			"Flint Contra o Genio do Mal ",
			"Eternamente Jovem",
			"Ladroes E Gatunos",
			"Goldie E O Pugilista",
			"Papai Ganso",
			"O Namorado da Minha Namorada",
			"Eloise No Plaza",
			"O Preço De Uma Vida",
			"O Menino E Os Piratas",
			"O Marco Derradeiro",
			"Um Senhor Estagiario",
			"Um Dia",
			"Planeta Do Tesouro ",
			"Amor Em Jogo",
			"Meu Amigo, O Dragao (1977)",
			"Pelos Campos da Vitoria ",
			"Keefer",
			"A Filha Do Presidente (2004)",
			"Feito Caes & Gatos",
			"Missao Maluca",
			"Quarteto Fantastico (2005)",
			"Philomena ",
			"Meninas Malvadas 2",
			"Dose Dupla",
			"O Guarda-Costas",
			"Alice Nao Mora Mais Aqui",
			"A Fonte Dos Desejos",
			"O Mordomo E A Dama",
			"O rei e o Aventureiro",
			"K9: Uma Aventura De Natal ",
			"Babe: O Porquinho Atrapalhado Na Cidade",
			"Shiloh: O Melhor Amigo",
			"Conrack",
			"A Força do Coraçao",
			"Naufragio ",
			"Valente (2012)",
			"Orca: A Baleia Assassina",
			"Terror Na Montanha Russa",
			"Brincando Com O Fogo",
			"Marcando Em Cima",
			"Casamento De Alto Risco",
			"Meu Passado Me Condena: O Filme",
			"Quase Feitos Um Para O Outro",
			"Presas No Suburbio",
			"O Pentelho",
			"Meu Amigo Panda",
			"Highlander 2: A Ressurreiçao",
			"Jeannie e Um Genio: 15 Anos Depois",
			"A Fantastica Fabrica de Chocolates",
			"Um Hospede Do Barulho",
			"A Vida Secreta De McCormick",
			"Loucademia De Policia",
			"Estranhos Vizinhos",
			"Quem Salvara Nossas Crianças?",
			"Deixe Ontem Para Tras ",
			"A Hora do Rush 2 ",
			"Pare o Casamento!",
			"Radio Flyer",
			"Promessas Defeitas",
			"Nosso Homem De Bond Street",
			"Super Snooper, Um Tira Genial",
			"O Disco Voador",
			"A cançao Primetida ",
			"O Rato que Ruge ",
			"Minha Mae Quer Que Eu Case ",
			"Rusty: O Grande Resgate",
			"Encontros E Desencontros (1979)",
			"O Homem de La Mancha ",
			"O unico Sobrevivente ",
			"Corina: Uma Baba Perfeita ",
			"O Mundo de Nicky ",
			"Mansao Mal-Assombrada ",
			"A Super Agente",
			"K-9: Um Policial Bom Pra Cachorro",
			"Camp Rock",
			"Brink!",
			"Viagem Ao Mundo Dos Sonhos",
			"A Convençao das Bruxas",
			"Um Homem Impossivel De Se Amar",
			"A Hora do Rush 3 ",
			"Um Amor Inesperado (2015) ",
			"Pequenos Espioes 4",
			"O Contador De Historias",
			"Zoando Na TV",
			"Os Trapalhoes Na Terra Dos Monstros",
			"Fuga Espetacular Do Ze Colmeia",
			"O Tempo Certo Do Amor",
			"A Maquina de Fazer Milhoes",
			"reclassificado para 12 anos ",
			"Lanterna Verde ",
			"O 13º Aniversario",
			"Zamora, Um Amor De Gorila",
			"Sonhos E Vingança",
			"Indiana Jones E O Templo Da Perdiçao",
			"As Desventuras De Merlin Jones",
			"A Menina E O Porquinho (1973)",
			"O Principe Valente",
			"Uma Dupla Quase Perfeita",
			"Police Story 2: Codinome Radical",
			"Tempo Esgotado",
			"Deu A Louca Nos Monstros",
			"De Volta Aos Embalos De 76",
			"Remo: Desarmado E Perigoso",
			"Marcas Do Destino",
			"Uma Aventura No Espaço",
			"Se Eu Fosse Voce",
			"Desventuras Em Serie",
			"Um Verao Diferente",
			"Coraçao de Papel",
			"F/X 2: Ilusao Fatal",
			"Quem Nao Corre, Voa",
			"Sem Medo De Viver",
			"Misterio No Bosque",
			"Sortilegios Do Amor",
			"O Extraordinario Marinheiro",
			"Angustia ",
			"A Nova Cinderela",
			"O Casamento De Romeu E Julieta",
			"Guerra Biologica",
			"Uma Garota Da Pesada",
			"A Vingança do Dragao",
			"Dois Lutadores Do Barulho",
			"Os Espioes Que Entraram Numa Fria",
			"Crianças De Valor",
			"O ultimo Dragao",
			"Talhado Para Campeao",
			"Abençoai As Feras E As Crianças",
			"O Amor e Mais Forte",
			"Bater ou Correr",
			"Do Outro Lado da Linha",
			"Bogus, Meu Amigo Secreto",
			"A Magia Das Fadas",
			"Meus Problemas Com As Mulheres",
			"Os Defensores",
			"A Vitoria do Silencio ",
			"As Mil e uma Noites arabes (1959)",
			"Xuxa & Os Trapalhoes em: O Misterio de Robin Hood",
			"As Crianças Que Ninguem Queria",
			"Uma Mistura Especial",
			"O Espiao Que Me Amava",
			"Ao Sul de Sumatra",
			"As Pontes do Toko-Ri",
			"Robinson Crusoe em Marte",
			"Epa! Cade o Noe?",
			"Annapolis",
			"Projeto China 2",
			"De Medico E De Louco Todo Mundo Tem Um Pouco",
			"Nos Somos Campeoes",
			"A Famila Kovack",
			"Minha Amiga Flicka",
			"No Tempo da Onça",
			"Perdido Pra Cachorro 2 ",
			"A Cura",
			"O Terminal",
			"Um Morto Muito Louco",
			"O ultimo Guerreiro Das Estrelas",
			"Atraidos Pelo Desejos",
			"O Rei Dos Reis",
			"Dama por um dia",
			"A Escola De Susto Do Gasparzinho",
			"King Kong (1976)",
			"Beniker Gang: Os Fugitivos",
			"40 Quilates",
			"A Turma De Charlie Brown",
			"A Felicidade Nao Se Compra ",
			"Zathura: Uma Aventura Espacial",
			"No Caminho Do Sucesso",
			"Desafio Mortal",
			"A Garota De Rosa-Shoking",
			"O Pequeno Polegar",
			"A Casa Do Espanto 2",
			"O Notavel Impostor ",
			"Buffy, A Caça Vampiros",
			"Vendaval Na Jamaica",
			"Hotel De Lua-De-Mel",
			"True Lies",
			"Os Picaretas",
			"Uma Aventura Em Oxford",
			"Gotcha: Uma Arma Do Barulho",
			"Ferias no Trailer",
			"Um Encontro Com Seu idolo",
			"O Noviço Rebelde",
			"Clube Dos Pilantras",
			"Um Tira no Jardim de Infancia 2",
			"Ramona e Beezus",
			"Sobrevivendo ao Natal",
			"Toy Story: Um Mundo De Aventuras",
			"Jumanji",
			"O Maskara",
			"A Enfermeira ",
			"Anjos Rebeldes ",
			"A ultima Fronteira ",
			"Um Presente Para Toda a Vida",
			"Mudança De Habito 2: Mais Loucuras No Convento",
			"Falcao: O Campeao Dos Campeoes",
			"Space Buddies: Uma Aventura No Espaço ",
			"Lembranças De Outra Vida",
			"Com Caipira Nao Se Brinca",
			"Os Embalos De Sabado Continuam",
			"O Homem De Button Willow",
			"Agencia Matrimonial",
			"Ta Chovendo Hamburguer 2",
			"E Se Fosse Verdade",
			"Titan",
			"A Volta Do Incrivel Hulk",
			"Os Vagabundos Trapalhoes",
			"A Historia De Oliver",
			"Esquadrao Classe A (1982)",
			"Ele E As Tres Noviças",
			"A Força do Amor ",
			"O ultimo Hurrah ",
			"Bilhete de Loteria",
			"Um Presente Para Helen",
			"O Dia De Folga Do Papai",
			"Braddock 3: O Resgate",
			"Allan Quartermain E A Cidade de Ouro Perdida",
			"O Fio Da Suspeita",
			"O Tunel",
			"Um Natal Muito, Muito Louco",
			"O Bicho Vai Pegar 2",
			"Xuxa Popstar",
			"O Encanto Do Natal",
			"Um Pequeno Romance",
			"O Espadachim de Siena",
			"So Para Solteiros",
			"Panico (1970)",
			"Meu Pe de Laranja Lima (1970) ",
			"Que Horas Ela Volta?",
			"O Amor Mora Ao Lado",
			"Verao De Ilusoes",
			"Os Aventureiros Do Fogo",
			"Kramer Vs. Kramer",
			"Perdido na Selva ",
			"Pulando a Vassoura",
			"Meu Namorado Perfeito",
			"Xuxa E O Tesouro Da Cidade Perdida",
			"A Coragem E A Paixao",
			"A Bomba Que Desnuda",
			"Alice no Pais das Maravilhas (2010)",
			"Ducobu 2",
			"O Reino Gelado ",
			"Um Diretor Contra Todos",
			"Asteroide",
			"Deu A Louca Nos Federais",
			"FX: Assassinato Sem Morte",
			"A Barbada Do Biruta",
			"Subindo Por Onde se Desce ",
			"Garoto-Formiga",
			"Quando O Coraçao Fala Mais Alto",
			"Quem e Harry Crumb!",
			"Memorias Do Pavor",
			"Sequestro Sem Pista",
			"O Espadachim ",
			"Grande Menina, Pequena Mulher",
			"Coraçao De Cavaleiro",
			"Velocidade Maxima",
			"Gasparzinho: O Fantasminha Camarada",
			"Parque Dos Dinossauros",
			"Ernest, Um Trapalhao Na Cadeia",
			"O Grande Roubo Da Brinks",
			"O Esporte Favorito Dos Homens",
			"Ela e a Poderosa",
			"Um Jardim Especial",
			"Aquamarine",
			"Por Amor Ou Por Dinheiro",
			"Uma Questao De Escolha",
			"Os Orfaos",
			"O Principe E O Vira-Lata",
			"Good Burger",
			"Regresso Do Vietna",
			"Travessia Selvagem",
			"Evelyn: Uma Historia Verdadeira",
			"Taxi 2",
			"O Senhor Dos Milagres",
			"Stargate: Herdeiros Dos Deuses Parte 1",
			"Alguem Muito Especial",
			"Robocop: O Policial Do Futuro",
			"Garota Esperta",
			"Rodolfo Valentino",
			"Lado A Lado (1998)",
			"O Quinto Elemento",
			"O Barco Do Amor",
			"O Suplicio de Lady Godiva",
			"Pode Chamar-me Mamae",
			"Os Noivos da Minha Noiva ",
			"Um Maluco Perdido No Espaço",
			"Pelo Amor De Benji",
			"Onde Estao Meus Filhos?",
			"Febre De Juventude",
			"Bill",
			"exceto para o RJ",
			"Snow Buddies: Uma Aventura No Gelo ",
			"O Pai Da Noiva",
			"Kate & Leopold",
			"Space Chimps: Micos No Espaço",
			"No Mundo Dos Dragoes",
			"Um Lobo Na Familia",
			"Atrapalhando A Suate",
			"Furia De Titas (1981)",
			"Muito Bem Acompanhada ",
			"Com A Bola Toda",
			"Batman: O Retorno",
			"Free Willy 2: A Aventura Voltou",
			"Monsieur Cognac",
			"O Inspetor Geral ",
			"Central Do Brasil",
			"Um Jogo De Vida E Morte",
			"Ali Baba E Os Quarenta Ladroes",
			"Transformers: O Lado Oculto da Lua",
			"Astro Boy",
			"A Cidade Do Halloween",
			"Com Amor E Ternura",
			"As Novas Aventuras De Flipper",
			"Quando Os Deuses Amam",
			"De Coniço e Sambura ",
			"Ate Que A Sorte Nos Separe",
			"Meu Marciano Favorito",
			"O Rapto Do Menino Dourado",
			"Ze Colmeia E A Invasao Dos Ursos Espaciais",
			"Eu, Minha Mulher E Minhas Copias",
			"Dois Farristas Irresistiveis",
			"Como Perder um Homem em 10 Dias",
			"Olha Quem Esta Falando",
			"High School Musical 2",
			"A Arca De Norman",
			"Duro De Agarrar",
			"Sem Amanha",
			"A Natividade",
			"Letra E Musica",
			"lankman: Um Super-Heroi Muito Atrapalhado",
			"Comando Para Matar",
			"Quem e Essa Garota?",
			"FernGully: As Aventuras De Zak E Crysta Na Floresta Tropical",
			"Os Dois Super Tiras Em Miami",
			"Rambo: Programado Para Matar",
			"Um Presente Especial",
			"Cara A Cara",
			"Assassinato Por Morte",
			"A Espada De DArtagnan ",
			"O Homem Do Futuro",
			"Vida Roubada",
			"Irmaos De Fe",
			"Maria, Filha De Seu Filho ",
			"Um Morto Muito Louco 2",
			"Desafiando Os Limites",
			"Fabrica De Loucuras",
			"O Moinho Negro",
			"Oitenta Passos Para a Felicidade",
			"Salome",
			"A Corrente do Bem",
			"Redescobrindo o Amor",
			"Treinadora Por Acaso",
			"O Retorno Da Familia Addams",
			"Duas Babas Nada Perfeitas",
			"A Dificil Arte Do Amor",
			"Um Lugar No Coraçao",
			"O Cavaleiro De Sherwood",
			"O Paraiso e Logo Ali",
			"Mocinho Encrenqueiro ",
			"Vai Que Cola: O Filme",
			"Maluca Paixao",
			"Um Homem, Uma Mulher E Uma Criança",
			"Brotinho Indocil",
			"O Terno de Dois Bilhoes de Dolares",
			"Rio",
			"O Castelo Do Medo ",
			"Dando Um Tempo ",
			"Lassie",
			"As Grandes Ferias",
			"Um Estranho A Bordo",
			"Uma Noite No Rio",
			"Sai de Baixo: O Filme",
			"Operaçao Zodiaco",
			"Piratas Modernos",
			"Charlie: Em Ritmo De Aventura",
			"Pode Me Chamar De Noel",
			"O Encontro Do Natal",
			"Rumo Ao Desconhecido",
			"Rabo de Foguete",
			"Edward Maos De Tesoura",
			"A Fuga Das Galinhas",
			"Zamora: Um Amor De Gorila",
			"Zelly E Eu",
			"Minha Vida, Meus Amore",
			"Kung Fu Panda",
			"Os Smurfs e a Vila Perdida ",
			"Os Tres Patetas (2012)",
			"Direito de Mae",
			"A Casa Inteligente",
			"Babe: O Porquinho Atrapalhado",
			"O Falcao Esta a Solta",
			"Dick Tracy",
			"Papai Noel Existe",
			"Musica e Romance ",
			"Alem Da Sala De Aula",
			"A Filha Do Chefe",
			"Rajada de Fogo",
			"Um Anjo Para O Natal",
			"Tres Espias Demais: O Filme ",
			"Turma da Monica: Laços ",
			"Madagascar 2",
			"O Resgate Do Papai",
			"A Princesa Prometida",
			"Madeline",
			"O Anjo Malvado",
			"O Caminho de Volta ",
			"Armadilha Amorosa ",
			"Os Fantasmas Trapalhoes",
			"Um Distinto Cavalheiro",
			"Os Pais, Os Filhos",
			"A Prova Suprema",
			"A Nave da Revolta",
			"O Esquadrao Secreto de Jackie",
			"Twister",
			"Matine: Uma Sessao Muito Louca",
			"O Mundo e das Mulheres",
			"Quo Vadis?",
			"Alvin E Os Esquilos",
			"Deu A Louca Na Branca De Neve",
			"Gol!",
			"Marcas De Uma Obsessao",
			"Uma Segunda Chance",
			"A Terra Que O Mundo Esqueceu",
			"Coraçoes Atormentados",
			"Instituto da Vingança",
			"Alvin e os Esquilos 2",
			"Aromas e Sensibilidade",
			"Godzilla (1998)",
			"O Trem Desgovernado (1999)",
			"Fuga De Atlantica",
			"O Predador",
			"Frankenstein",
			"A Vida Secreta Na Kathy McCormick",
			"Codigo De Honra 2: Controle Hostil",
			"O Abismo Negro",
			"Robos",
			"Como Agarrar Meu Ex-Namorado",
			"La Bamba",
			"O Pequeno Hercules",
			"Final Fantasy",
			"American Kickboxer: Duelo Decisivo",
			"Diga O Que Quiserem",
			"A Trilha Da Pantera-Cor-De-Rosa",
			"O Ocaso De Uma Alma",
			"O Bicho Vai Pegar 4 ",
			"Outono Em Nova York",
			"Sinbad: A Lenda Dos Sete Mares",
			"Johnny Kapahala: De Volta Ao Havai",
			"Bebes Genias",
			"O Casamento Dos Trapalhoes",
			"Os Trapalhoes No Auto Da Compadecida",
			"John Escandaloso",
			"Meu Adoravel Fantasma",
			"O Arqueiro E A Feiticeira",
			"Operaçao Big Hero",
			"Por agua Abaixo",
			"Tudo Que Uma Garota Quer",
			"Esqueceram De Mim 4",
			"Os Caça-Fantasmas 2",
			"A Mulher Que Ele Amou",
			"Os Cavaleiros Da Tavola Redonda",
			"Os Tres Mosqueteiros Trapalhoes",
			"O Sentido do Amor ",
			"H20: Meninas Sereias ",
			"Colisao de Planetas ",
			"No Mundo da Lua ",
			"Jump In!",
			"Se O Meu Fusca Falasse",
			"Promessas Desfeitas",
			"Papai Playboy",
			"Roma, Convite Ao Amor",
			"O Sonho Que Eu Vivi",
			"Coraçao de Tinta: O Livro Magico ",
			"Tudo e Todas as Coisas",
			"Madagascar",
			"Vovos Em Hollyrock",
			"O Anjo Da Guarda",
			"O Reserva Do Papai Noel",
			"Romeu & Julieta",
			"Nao Diga Quem Sou Eu",
			"Uma Noite Com O Rei Do Rock",
			"Asas Para O Ceu",
			"Perdido Pra Cachorro 3 ",
			"Deu A Louca Na Cinderela",
			"Minha Vida Com Lucky",
			"Top Gang: Ases Muito Loucos",
			"Uma Fazenda Do Barulho",
			"A Festa do Monstro Maluco ",
			"Carros 2",
			"Tres Solteiroes E Um Bebe",
			"O Mentiroso",
			"Hospede Por Acaso",
			"Escandalos No Hotel",
			"Viper",
			"Robur, O Conquistador",
			"Os Homens Preferem As Loiras",
			"Encrenca Em Cheio",
			"Caminhos do Coraçao: 5 Dias para o Destino ",
			"Alex Rider Contra O Tempo",
			"A Dor De Uma Saudade",
			"Uma Mistura Diferente",
			"Barrados No Baile: O Filme",
			"Jogada Certa",
			"Gasparzinho E Wendy",
			"Um Visto Para O Ceu",
			"Tahiti ",
			"Um Homem de Familia (2017)",
			"Ratatouille",
			"Didi, O Caçador De Tesouros",
			"Power Rangers: O Filme",
			"A Ilha Do Tesouro (1950)",
			"Legioes Do Nilo",
			"Twitches: As Bruxinhas Gemeas",
			"Os Aventureiros Do Bairro Proibido",
			"Como Eliminar Seu Chefe",
			"Troca De Maridos",
			"A Louca Escapada",
			"O Fruto de uma Paixao",
			"A Amiga da Onça ",
			"A Fabulosa Gilly Hopkins",
			"Enquanto Voce Dormia",
			"A Familia Da Noiva",
			"Space Chimps 2: O Retorno De Zartog ",
			"O Genio Do Vidoegame",
			"Herois Muito Loucos",
			"Suplicio de Uma Saudade ",
			"O Cisne Negro",
			"Mesmo Assim Eu Te Amo ",
			"Meu Mestre, Minha Vida",
			"Meu Sobrinho e Um Terror",
			"Dupla Traiçao",
			"Segredos De Mae E Filha",
			"Em Busca Da Fama",
			"Robotech",
			"O Amor Nao Tira Ferias",
			"Benji",
			"O Fofoqueiro",
			"Feira de Ilusoes ",
			"Resgate de uma Vida",
			"O Resgate De Lauren Mahone",
			"Surpresas Do Coraçao",
			"Crepusculo De Aço",
			"O Maravilhoso Homem Que Voou",
			"Um Romance Muito Perigoso",
			"Estranhos na Cidade",
			"Zorro, O Destemido",
			"Esqueceram de Mim 2: Perdido em Nova York",
			"Didi, O Cupido Trapalhao",
			"Irmaos Gemeos",
			"O Despertar De Rita",
			"Sortilegios de Amor",
			"Voando Alto",
			"Namorada De Aluguel",
			"Halloweentown: O Portal",
			"O Natal Da Familia Monstro",
			"O Grande Amor De Nossas Vidas",
			"Lua Negra, O Super Carro",
			"A Dama De Vermelho",
			"O Estado Interessante De Papai",
			"Os Turbantes Vermelhos",
			"Recem Casados",
			"O Ceu De Outubro",
			"Salve-me Quem Puder",
			"Unidos Para Vencer",
			"Ao Mestre, Com Carinho",
			"Transformers: O Filme",
			"Black Beauty: O Potro Negro",
			"Mercado De Coraçoes",
			"A Maravilhosa Fabula de Branca de Neve e os Sete Anoes ",
			"somente para SP)",
			"O Reino Proibido ",
			"Um Principe Em Minha Vida",
			"Maquina Quase Mortifera",
			"Antes So Do Que Mal Acompanhado",
			"Uma Razao Para Viver",
			"A Lontra Travessa",
			"Tres Estrelas e um Coraçao",
			"Andy Hardy Cowboy ",
			"Ta Dando Onda",
			"Meu Pe De Laranja Lima",
			"Foi Sem Querer",
			"Sheena, A Rainha Da Selva",
			"A Caça Ao Balao",
			"Os Guardas-Florestar",
			"Beleza Oculta",
			"Cine Holliudy 2: A Chibata Sideral",
			"Milagre Na Rua 34",
			"O Expresso Do Chicago",
			"Funeral Em Berlim",
			"Uma Garota Encantada",
			"A Bela E A Fera: O Natal Encantado ",
			"Tubarao 87: A Vingança",
			"A Princesa e o Plebeu",
			"O Resgate Da Lauren Mahone",
			"O Pirata Real",
			"Taina: A Origem ",
			"Hotel Transilvania 2",
			"Onde Nasce a Esperança",
			"Construindo Uma Carreira",
			"O Galinho Chicken Little",
			"Selvagem",
			"Mamae Nao Quer Que Eu Case",
			"Brincando Com Fogo",
			"O Tesouro De Matecumbe",
			"Caroline?",
			"A Lenda do Revolver Dourado ",
			"Fantasmas da Fuzarca ",
			"Sempre Amigos",
			"Rusty, O Grande Resgate",
			"Batman, O Retorno",
			"Intocaveis (2011)",
			"Missao Impossivel",
			"Bilhete Premiado",
			"Sem Jeito para Morrer",
			"A Guerreira De Marsales",
			"Eu, Voce, Ele E Os Outros",
			"O Direito De Matar: O Caso De Karen Ann Quinlan",
			"A Encruzilhada",
			"A Gatinha Que Eu Quero",
			"A Bela E A Fera (1962)",
			"A Seleçao ",
			"Surpresa em Dobro",
			"Nunca e Tarde Para Amar",
			"Robin Hood: O Principe Dos Ladroes",
			"Frankenstein: O Sonho Nao Acabou",
			"Natal Na Neve",
			"Esses Homens Maravilhosos E Suas Maquinas Voadoras",
			"O Prisioneiro De Casbah",
			"No Paraiso Do Havai",
			"Zack & Cody: O Filme ",
			"Linda de Morrer",
			"Johnny Tsunami: O Surfista Da Neve",
			"A Filha Do Presidente (1998)",
			"Ensina-me Crescer",
			"Panico No Atlantico Express",
			"Loucos De Dar No",
			"Amizade Inesperada",
			"O Pequeno Unicornio",
			"Dois Loucos No Tempo",
			"Os Implacaveis",
			"Orca, A Baleia Assassina",
			"De Volta Para Casa (2012) ",
			"Confusao No Velho Oeste",
			"Viagem Infernal",
			"Caestronautas ",
			"Resgate Abaixo de Zero",
			"Um Lugar Chamado Notting Hill",
			"aguia De Aço 4: O Combate Final",
			"Um Viuvo Trapalhao",
			"O Principe Pirata ",
			"Segurança de Shopping",
			"Amor as Escuras",
			"Feliz Natal, Drake & Josh ",
			"Nao Mexa Com A Minha Filha",
			"A Garota Do Adeus",
			"O Filho De Robin Hood",
			"Os Homens Preferem as Louras",
			"Meu Pai, Meu Heroi",
			"Sabrina Vai A Roma",
			"Hercule E Sherlock",
			"Quem Ve Cara Nao Ve Coraçao",
			"As Coisas Mudam",
			"A Filha Da Pecadora",
			"Uma Historia De Amor E Campeoes",
			"Derby: A Corrida da Esperança",
			"Sonhando Com A Fama",
			"Bullitt",
			"A Deliciosa Viuvinha",
			"Trinity e Seus Companheiros ",
			"Um Faz de Conta Que Acontece",
			"O Milagre Dos Caes",
			"Um Amigo Diferente",
			"Maneco, o Supertio",
			"Zarak",
			"Jack Hunter E O Olho Do Enigma",
			"A Historia De Waylon",
			"Confusao Na Australia",
			"Dr. Hollywood: Uma Receita De Amor",
			"Marujos Muito Loucos",
			"Guerreiro Americano 3",
			"Uma Linda Condessa",
			"Uma Vida Inesperada",
			"Bandeirantes De Beverly Hills",
			"Gidgety ja e Adulta",
			"Pequenos Espioes 3D",
			"Joao E Maria",
			"Conflitos No Inverno",
			"Assassinato No Voo 502",
			"O Mercador De Almas",
			"Hans Christian Andersen",
			"Lizzie McGuire: Um Sonho Popstar",
			"Alguma Coisa Em Comum",
			"Os Tres Fugitivos",
			"O Menino Que Queria Ser Anjo",
			"O Tesouro do mar",
			"Uma Casa De Pernas Pro Ar",
			"Um Principe Em Minha Vida 4",
			"Naufrago",
			"O Melhor dos Inimigos",
			"Cavalo de Guerra",
			"Impacto Profundo",
			"Sequestro Sem Resgate",
			"Cegonhas: A Historia Que Nao Te Contaram",
			"Monstros Vs. Alienigenas",
			"Agente 86",
			"Presente De Grego",
			"A Força Da Vingança",
			"Meninas Malvadas",
			"Um Time Bom De Bola",
			"O Pequeno Grande Time",
			"Freejack: Os Imortais",
			"Dragnet: Desafiando o Perigo",
			"Um Fantasma Fora De Hora",
			"A Morte Vem Do Kilimanjaro",
			"As Aventuras de Sharkboy e Lavagirl",
			"Uma Folga Para Mamae",
			"Punhos De Aço",
			"M.A.S.H.",
			"Se Eu Fosse Voce 2",
			"Uma Questao Familiar",
			"Mary Poppins",
			"Por Um Corpo De Mulher",
			"Roleta Russa",
			"Os Trapalhoes no Planalto dos Macacos",
			"Jogos de Vida",
			"Mulheres e Diamantes ",
			"Alice Atraves do Espelho (2016) ",
			"To Ryca",
			"PePequeno ",
			"Os Trapalhoes E A arvore Da Juventude",
			"Jamaica Abaixo de Zero",
			"Viagem Clandestina",
			"Aventura No Espaço",
			"Feitiço Branco",
			"Outback: Uma Galera Animal ",
			"Geraçao X",
			"Meu Papai e Noel 3 ",
			"Crianças Adotadas",
			"No Reinado Da Guilhotina",
			"Lutando Pela Vida ",
			"Tio Papi",
			"Meu Adoravel Android",
			"O Heroi do PT-109 ",
			"Treinando o Papai",
			"Bingo, Esperto Pra Cachorro",
			"Pequenos Ladroes De Cavalos",
			"O Cavaleiro Azul",
			"Gigot",
			"A Corrida Para Stephanie ",
			"Tarzan (1932)",
			"A Formula: O Filme ",
			"Um Namorado Para Minha Mulher",
			"Tudo O Que Uma Garota Quer",
			"Ace Ventura 2: Uma Maluco Na africa",
			"Suki Na Savana",
			"Menino Maluquinho 2 ",
			"O Grande Assalto (1993)",
			"Unidos Por Um Ideal",
			"A Dama e os Bandidos ",
			"e Fada",
			"Ferias da Familia Johnson",
			"Voce Outra Vez",
			"Quando os Anjos Cantam",
			"Duplex",
			"Crossroads: Amigas Para Sempre",
			"Cruzeiro Do Terror",
			"A Familia Kovack",
			"Quem e Esta Garota?",
			"Um Dinstinto Cavalheiro",
			"Baby, O Segredo Da Lenda Perdida",
			"Milhas Desesperadoras",
			"Chico Rei",
			"Barbie: Lago Dos Cisnes",
			"Jack Hunter E O Tesouro Perdido",
			"O Resgate De Jessica",
			"Desta Vez Te Agarro",
			"Um Cao Maravilhoso",
			"Famoso Pra Cachorro",
			"Hercule & Sherlock ",
			"Cadillac Azul",
			"Perigosamente Juntos",
			"Annie",
			"Tres Grandes Amigos ",
			"Uma Manha Gloriosa",
			"Billy Stone e o Medalhao Magico",
			"Chestnut: O Heroi Do Central Park",
			"Naufragio No Pacifico",
			"O Cinderelo Trapalhao",
			"Ela Vai Ter Um Bebe",
			"Black Beauty, O Potro Negro",
			"Lili",
			"Sonho Realizado",
			"Taxi",
			"Belas E Ferozes",
			"O Principe Do Sol",
			"Gatinhas E Gatoes",
			"O Rei Dos Magicos",
			"Um Homem de Familia (2016)",
			"Um Tira Muito Suspeito",
			"Curso De Verao",
			"Marcada Para Morrer",
			"Star Wars Episodio 4: Uma Nova Esperança",
			"Escravos da Babilonia",
			"A Barcaça Perdida",
			"Liçoes Para Toda A Vida ",
			"Vitorias de uma Vida",
			"So A Verdade Cura",
			"Do Que As Mulheres Gostam",
			"A Grande Aventura",
			"Uma Dupla Perfeita",
			"Tres Vezes Amor",
			"Nossa Querida Baba",
			"O Peste",
			"Meu Papai e Noel",
			"A Maldiçao Do Halloween",
			"A Admiradora Secreta",
			"Karate Kid 3: O Desafio Final",
			"Lady Reporter",
			"Moscou Em Nova York",
			"Sinfonia Eterna ",
			"As Patricinhas De Beverly Hills",
			"Em Busca Da Princesa Dos Mitos",
			"Quem e Harry Crumb?",
			"Memorias de Um Homem Invisivel",
			"Codigo De Honra",
			"Ardida Como Pimenta",
			"Meu Coraçao Canta",
			"O Brilho do Grande Canyon ",
			"A Mascara do Zorro ",
			"Armaçoes do Amor",
			"Monstros S.A. ",
			"Irma Dulce",
			"O Fugitivo",
			"As Coisas Engraçadas Do Amor",
			"Nunca Fui Santa",
			"Aviao Foguete X-15",
			"As Aventuras de David Copperfield",
			"Em Meus Sonhos",
			"Tudo Por Uma Esmeralda",
			"Tarzan Em Manhattan",
			"A Amante",
			"Meu Avo, Meu Amigo",
			"48 Horas",
			"Meus Dois Carinhos",
			"Em Busca da Vitoria",
			"A Deusa Selvagem",
			"Tarzan, o Magnifico",
			"Procurando Nemo",
			"Programa de Proteçao para Princesas",
			"Marley & Eu",
			"Taina: Uma Aventura Na Amazonia",
			"Amor Sem Fronteiras",
			"Quem Tudo Quer... Tudo Perde",
			"O Bagunceiro Arrumadinho",
			"Don Juan era Aprendiz",
			"Nossa Uniao, Muita Confusao ",
			"Ninguem Segura Este Bebe",
			"As Aventuras Do Capitao Zoom No Espaço",
			"Ze Colmeia E Seu Voo Magico",
			"Diabruras Dos Anjos Rebeldes",
			"Operaçao Crossbow",
			"Projeto Jensen ",
			"O Garoto Invisivel (2014) ",
			"Coincidencias do Amor",
			"O Expresso Polar ",
			"Casa Comigo?",
			"Meu Primeiro Amor",
			"O Gigante De Ferro ",
			"Footloose: Ritmo Louco",
			"O Filho de Lassie",
			"A Mocidade e Assim",
			"Quatro Amigas E Um Jeans Viajante",
			"Um Craque Animal",
			"O Criado: Um Conquistador Em Apuros",
			"Crazy People: Muito Doidos",
			"Tres Vidas Em Fuga",
			"O Tenente Era Ela",
			"Uma Amizade Inesperada",
			"Ed: Um Macaco Muito Louco",
			"Os Descasados",
			"O Homem Certo",
			"Perdidos na Selva ",
			"Castelos de Gelo (2010)",
			"A Princesa e o Sapo",
			"O Menino da Porteira ",
			"Se Meu Fusca Falasse",
			"Pentathlon: Uma Disputa Mortal",
			"Caçadores De Marfim",
			"A Casa de cha do Luar de Agosto ",
			"Tudo Por Uma Herança",
			"Quando As Metralhadoras Cospem",
			"Maxie",
			"Maria do Carito ",
			"Plano B (2010)",
			"Uma Noite No Museu 2",
			"Voce Nao Pode Beijar A Noiva",
			"Como Viajar Com O Mala Do Seu Pai",
			"Bambi 2: O Grande Principe Da Floresta ",
			"Confidencias a Meia-Noite",
			"O Julgamento Do Incrivel Hulk",
			"A Mulher do Chefe",
			"Uma Cilada Para Roger Rabbit",
			"Os Dois Supertiras Em Miami",
			"O Destino De Uma Paixao",
			"Nasce Uma Estrela (1937)",
			"Principe da Persia: As Areias do Tempo",
			"Confusao Pra Cachorro",
			"Os Flintstones Em Viva Rock Vegas",
			"O Destemido Senhor Da Guerra",
			"Um Caminho Para Dois",
			"Meu Querido Presidente ",
			"Os Direitos Femininos",
			"A Força De Um Sonho",
			"Soltando Os Cachorros",
			"ABC Do Amor",
			"Dinossauro",
			"The Wonders: O Sonho Nao Acabou",
			"Uma Secretaria de Futuro",
			"Comandos Em Açao",
			"O Sonho Impossivel",
			"O Aventureiro de Hong-Kong",
			"Carmem",
			"O Fada do Dente",
			"Anastasia",
			"Robocop 3",
			"Loucuras de um Milionario",
			"Harpia ",
			"Gente Grande",
			"Acampamento do Papai",
			"Cada Um Tem a Gemea Que Merece",
			"Air Bad Contra-Ataca",
			"A Força",
			"Negocios Em Familia",
			"A Baleia Assassina",
			"Passageiro 57",
			"Desta Vez Eu Te Agarro",
			"Dois Espioes E Um Bebe",
			"Simbad Contra o Olho do Tigre",
			"O Pecado Mora Ao Lado",
			"A Fuga do Planeta dos Macacos",
			"Rochedos de Morte",
			"As Aventuras De Tintim",
			"As Aparencias Enganam",
			"O Pequeno Stuart Little",
			"Elvira, A Rainha Das Trevas",
			"Menino Maluquinho 2: A Aventura",
			"A Vingança De Milady",
			"Voando Para o Amor ",
			"Meu Pai Heroi",
			"O Preço Do Desafio",
			"A Trilha Do Bravo",
			"Tubarao 2",
			"Seu Nome e Jonas",
			"Onde Estavas Quando As Luzes Se Apagaram?",
			"Doo Savage ",
			"Ondas da Vida",
			"Corra Que A Policia Vem Ai 2 1/2",
			"Detetives Em Anjo",
			"Encurralado",
			"80 Passos Para a Felicidade",
			"filme mais curto para ajuste de grade",
			"Tudo e Possivel",
			"Cachorro Vampiro ",
			"FormiguinhaZ",
			"Aracnofobia",
			"Pagando Pecados",
			"Os ETs Caretas",
			"Sob o Mesmo Ceu",
			"Planeta 51",
			"O Livro Magico",
			"Patrick",
			"Skyrunners ",
			"A Princesa Xuxa E Os Trapalhoes",
			"Cinderelo Trapalhao",
			"Rocketeer",
			"Marcada Pelo Passado",
			"O Preço De Desafio",
			"Os Lordes De Flatbush",
			"Africa Express",
			"Mowgli, o Menino Lobo ",
			"Corra Que A Policia Vem Ai",
			"Os Trapalhoes Na Guerra Dos Planetas",
			"Luz Da Minha Vida",
			"A Herdeira Da Mafia",
			"Tal Pai, Tal Filho",
			"Uma Aventura Na Arabia",
			"Historia De Chicago",
			"A Nova Viagem De Simbad",
			"Inocencia",
			"Dois Destinos se Encontram",
			"O Menino e o Puma",
			"Tudo Por Amor",
			"Uma Familia Quase Perfeita",
			"Espioes Sem Rosto",
			"Criaturas 2",
			"Banze Na Russia",
			"Ameaça No Supersonico",
			"Aventura Submarina",
			"Operaçao: Salvem Os Golfinhos",
			"As Aventuras De Chatran",
			"Aracanofobia",
			"As Ferias do Papai",
			"O Paizao",
			"Peter Pan: De Volta a Terra Do Nunca",
			"Uma Liçao De Coragem",
			"Aluga-se Para O Verao",
			"Um Show De Verao",
			"Uma Loira Em Apuros",
			"Historia Sem Fim",
			"Honra E Gloria",
			"Um Amor de Vizinho",
			"Jurassic Park: Parque dos Dinossauros ",
			"Vovo...Zona",
			"Johnny",
			"Xuxa Requebra",
			"Nos Termpos Do Rei Arthur",
			"Resgate Do Saara",
			"A ultima Viagem Da Arca De Noe",
			"Cherry 2000",
			"Quando O Coraçao Bate Mais Forte",
			"Os Saltimbancos Trapalhoes",
			"Encontro as Escuras",
			"Butch Cassidy",
			"Para Todo O Sempre",
			"Duelo Na Selva",
			"Familia Por Acaso",
			"Avalon High ",
			"As Aventuras De Hubert, O Cao Herdeiro",
			"Meus Amigos Dinossauros 2",
			"A Lenda Da Espada Magica",
			"Desiree, O Amor De Napoleao",
			"Encontro de Amor",
			"O Casamento do Meu Melhor Amigo",
			"Os Fantasmas Se Divertem",
			"Uma Aventura Magica",
			"O Negocio e Sobreviver",
			"Felizes Para Sempre",
			"O Menino e o Delfim",
			"A Grande Aventura de Lassie ",
			"Jogador Nº 1",
			"Os Delirios De Consumo De Becky Bloom",
			"Diario De Uma Adolescente",
			"Vingança Forçada",
			"O Cachorro Branco",
			"As Loucuras De Jerry Lewis",
			"Sangue Ardente",
			"A Vingança das Damas de Honra",
			"Buddy, Meu Gorila Favorito",
			"O Paraiso Te Espera",
			"O Erro De Susan Slade",
			"Como Se Fosse a Primeira Vez",
			"Police Story",
			"Sheena, A Rainha das Selvas",
			"Os Fantasmas Contra Atacam",
			"Jugger Naut: Inferno Em Alto Mar",
			"Um Grande Gozador",
			"Chamada para um Morto ",
			"Taxi (2004)",
			"A Sogra",
			"A ultima Palavra",
			"Procura-se Susan Desesperadamente",
			"Começar De Novo",
			"Homens do Deserto",
			"Sofrendo da Bola",
			"Fora do Rumo",
			"Mamae Precisa Casar",
			"Garota Boa De Bola",
			"Projeto China 2: A Vingança",
			"O Inocente",
			"Uma Linda Condenssa",
			"Temporada Brilhante",
			"O Juramento do Zorro ",
			"O Segredo Dos Animais ",
			"O Diabo Veste Prada",
			"Feitiço das Gemeas",
			"O Preço da Conquista",
			"Robin Hood de Chicago",
			"A Sereia do Alaska ",
			"Os Seis Signos Da Luz",
			"Anastasia (1997)",
			"Dois Velhos Mais Rabugentos",
			"Dois Contra o Oeste",
			"Espionagem Internacional",
			"Um Pequeno Inconveniente",
			"Tudo Que Quero ",
			"As Feras Da Musica 2",
			"O Principe das Mulheres",
			"Um Peixe Chamado Wanda",
			"Nanny McPhee e as Liçoes Magicas",
			"Uma Prova de Amor",
			"Querem Acabar Comigo",
			"Finn: Amigo Pra Cachorro",
			"O Genio Do Video Game",
			"A Vida Secreta De Kathy McCormick",
			"Fuja, Puma, Fuja",
			"Harvey, o Bombeiro ",
			"A Bela Ditadora ",
			"em novo horario, apos o Jornal Hoje ",
			"Cidades de Papel",
			"Vira-Lata",
			"Em Busca Do Coraçao De David",
			"Cocoon: O Regresso",
			"Um Ladrao Na Familia",
			"A Princesa E O Pebleu",
			"Num Lago Dourado",
			"A Fantastica Ilha do Tesouro",
			"O Pequeno Nicolau",
			"A Garota Dos Meus Sonhos",
			"Atraidos Pelo Perigo",
			"Viagem Fantastica",
			"Ursinhos Carinhosos 2",
			"Os Titas Voltam a Luta Na Atlantida",
			"Viuvinha Indomavel",
			"Um Presente Para Heidi",
			"Os Meus, os Seus, os Nossos",
			"inedito na Globo; ex-RecordTV)",
			"Cupido: A Magia Do Amor",
			"Comando Estrategico",
			"Xuxa E Os Trapalhoes Em O Misterios De Robin Hood",
			"Nao Diga Quem Eu Sou",
			"O Barco Do Amor: O Dia Dos Namorados",
			"Inspetor Faustao E O Mallandro",
			"A Lenda Dos Desaparecidos",
			"Nao me Mandem Flores",
			"O Otario e a Vigarista",
			"Indiscreta",
			"Os Quatro Da Ave Maria",
			"Uma Liçao Para Nao Esquecer",
			"O ultimo Dinossauro",
			"Minha Espada, Minha Lei",
			"A Garota De Las Vegas",
			"As Ferias Da Familia Robinson",
			"Aterrissagem De Alto Risco",
			"Elvira: A Rainha Das Trevas",
			"Uma Foca Em Minha Casa",
			"Mulher Ate O Fim",
			"O Incrivel Homem Do Espaço",
			"Carencia De Amor",
			"Caravana Da Coragem: Uma Aventura Ewok",
			"O Mundo e Da Mulher",
			"Os Monkees Estao Chegando ",
			"O ultimo Inquilino",
			"Virtude Selvagem",
			"Os Homens do Planeta Attia",
			"Situaçao Critica, Porem Jeitosa",
			"O Filho de Simbad",
			"O Traquina",
			"O Retorno De Prancer",
			"Um dia de sol",
			"Beethoven 2",
			"Halloweentown 2: A Vingança De Kalaba",
			"O Homem Invisivel",
			"Laços De Ternura",
			"Papai Tambem te ama ",
			"Ensinando a Viver",
			"Um Cachorro Para Dois",
			"Eragon",
			"Noiva em Fuga",
			"Noivas Em Guerra",
			"Santa Buddies: Uma Aventura de Natal ",
			"American Mall",
			"Ace Ventura: Um Detetive Diferente",
			"O Melhor De Todos Os Natais",
			"O Incrivel Monstros Trapalhao",
			"O Dragao E O Feticeiro",
			"Elmer",
			"Junior",
			"Uma Secretaria Do Futuro",
			"Willow: Na Terra Da Magia",
			"As Ferias do Pequeno Nicolau",
			"As Aventuras De Sammy ",
			"Didi Quer Ser Criança",
			"Cop Dog: O Cao Policial ",
			"Ace Ventura 2: Um Maluco Na africa",
			"As Minas Do Rei Salomao",
			"Uma Mistura Especial 2",
			"Minha Terra, Minha Vida",
			"Que Sorte Danada!",
			"Ainda nao Comecei a Lutar",
			"O Traquiana",
			"Zorro e os Tres Mosqueteiros ",
			"Espelho, Espelho Meu",
			"A Hora Da Virada",
			"Um Professor Quase Perfeito",
			"Um Vagabundo Na Alta Roda",
			"Os Diamantes Sao Eternos",
			"Os Irmaos Cara-De-Pau",
			"Voando Para Marte",
			"Doc Savage, o Homem de Bronze",
			"Quem Mal Anda, Mal Acaba ",
			"Encontro de Casais",
			"Em Busca do Baile",
			"Superman 2: A Aventura Continua",
			"Um Sem Juizo, Outro Sem Razao",
			"Um Amor De Elefante",
			"O Golfinho: A Historia De Um Sonhador ",
			"em novo horario, apos o Video Show ",
			"A Proposta (2009) ",
			"As Loucuras de Dick e Jane (2005)",
			"A Estranha Vida de Timothy Green",
			"Mais Do Que Amigos",
			"Dois Loucos Com Sorte",
			"Corruptos E Sanguinarios",
			"Maria: Mae Do Filho De Deus",
			"Um Ninja Da Pesada",
			"Um Natal Atribulado",
			"Os Tres Reis Magos Em Los Angeles",
			"Antes Tarde Do Que Nunca",
			"Tudo Começou com uma Troca",
			"Inimigos De Infancia",
			"Irmao Urso 2 ",
			"Turbo: Power Rangers 2",
			"Kingpin: Estes Loucos Reis Do Boliche",
			"Agente Duplo",
			"Retrato De Modelo",
			"A Morte Do Kilimanjaro",
			"Periscopio a Vista",
			"Invictus ",
			"Uma Professora Muito Maluquinha ",
			"Missao Condor",
			"Houve Uma Vez Um Verao",
			"Rompendo Correntes",
			"A Historia de Jaco e Jose",
			"O Pequeno Principe (2016)",
			"Garoto-Formiga 2",
			"Ensina-me A Crescer",
			"No Limiar Do Espaço",
			"Quarteto Fantastico E O Surfista Prateado",
			"A Familia Do Futuro",
			"O Trem Desgovernado",
			"Uma Noite No Bale",
			"Tudo Começou em Napoles",
			"um filme nunca visto pela TV brasileira ",
			"As Viagens de Gulliver",
			"O Que Esperar Quando Voce Esta Esperando",
			"Gotcha. Uma Arma do Barulho",
			"Louca Escapada",
			"Autor Em Familia",
			"As Incriveis Peripecias Do onibus Atomico",
			"O Mago De Bagda",
			"O som da Alegria ",
			"Setima Cavalaria ",
			"A ultima Palavra (2017) ",
			"Operaçao Baba",
			"O Grande Milagre",
			"Click",
			"Patch Adams: O Amor e Contagioso",
			"O Fim Do Planeta Marte",
			"Perigo Na Noite",
			"Benji, O Perseguido",
			"Lafitte, O Corsario",
			"O Grinch (2000) ",
			"Universidade Monstros ",
			"Tarzan E Jane",
			"Uma Familia Inesperada",
			"A Cidade Dos Desiludidos",
			"Caça Ao Balao",
			"Mercenarios das Galaxias",
			"A Pantera Cor-de-Rosa 2 ",
			"Escola Da Vida",
			"O Jardim Secreto",
			"Anjo Da Guarda",
			"Essas Garotas",
			"Diamantes",
			"O Rapaz Embalado Em Plastico",
			"Uma Experiencia Extraordinaria",
			"Heidi ",
			"E ultima Girafa ",
			"Farra Musical",
			"A Nova Transa Da Pantera Cor-De-Rosa",
			"Tex, Um Retrato Da Juventude",
			"Perfeiçao",
			"O Fator Netuno",
			"Anaguas a Bordo",
			"A Grande Vitoria",
			"Amor Por Acidente",
			"Dr. Dolittle",
			"Pateta: O Filme ",
			"Um Sem Juizo Outro Sem Razao",
			"Ato De Amor",
			"Onde Florescem os Lirios",
			"Nas Areias do Deserto",
			"A Gangue Zip Zap",
			"O Genio Do Videogame",
			"Caramuru: A Invençao Do Brasil",
			"Um Dia A Casa Cai",
			"Mad Max: Alem Da Cupula Do Trovao",
			"O Milagre na rua 34 ",
			"Oddball e os Pinguins ",
			"P.S. Eu Te Amo",
			"Paulie, O Papagaio Bom De Papo",
			"Homens De Branco",
			"Na Trilha Dos Apaches",
			"Um Longo Regresso",
			"O Habito Nao Faz O Monge",
			"A Casa Do Espanto (1985)",
			"futebol",
			"O Maior Amor do Mundo",
			"Lilo & Stitch",
			"O Homem Da California",
			"A Detetive E O Filho",
			"A Morte vem no Kilimanjaro",
			"Mercado pela Sarjeta ",
			"Alexandre e o Dia Terrivel, Horrivel, Espantoso e Horroroso",
			"Meu Amigo, O Pe Grande",
			"A Chave Magica",
			"Karate Kid 2: A Hora Da Verdade Continua",
			"O Natal Do Maluco Ernest",
			"Joga A Mamae Do Trem",
			"O Salsicha Campeao ",
			"Caçadores De Dragoes",
			"No Ritmo Da Dança",
			"Krull",
			"Gladiador: O Desafio",
			"O Mundo Encantado ",
			"Ela Disse, Ele Disse (2019) ",
			"A Cegonha Nao Pode Esperar",
			"Duro De Matar",
			"A Nova Transa da Pantera-Cor-de-Rosa",
			"Anjos da Vida: Mais Bravos Que o Mar ",
			"Jornada ao Reino Africano ",
			"Um Amor de Vizinha",
			"Um Momento Pode Mudar Tudo",
			"Charlie, Em Ritmo De Aventura",
			"Mano A Mana: O Filme",
			"3 Ninjas Do Barulho",
			"Eu Acredito Em Gnomos",
			"A Lenda De Billie Jean",
			"Crueis Sao Os Homens",
			"Escola De Sereias",
			"A Ressurreiçao de Gavin Stone",
			"Fazenda dos Cisnes ",
			"Festa no Ceu",
			"Meu Namorado Do Futuro",
			"O Segredo Do Fantasma",
			"Nos Tempos Do Rei Arthur",
			"Um Divorcio Complicado",
			"Braddock 2: O Inicio Da Missao",
			"Terra II",
			"Os Primeiros Homens na lua ",
			"Pai em Dose Dupla",
			"O Dilema",
			"Rei dos Reis",
			"Sonhos Dourados",
			"A Culpa e das Estrelas",
			"Confissoes De Uma Adolescente Em Crise",
			"Ferias Frustadas De Natal",
			"Controle Remoto",
			"O Cisne Negro (1942)(SP) ",
			"Pare, Olhe e Ria ",
			"O Incrivel Livro De Hipnotismo De Molly",
			"Um Amor Perfeito",
			"Guerreiros Da Virtude",
			"Invasores Do Espaço",
			"Ninja Justiceiro",
			"O Vagabundo De Um Milhao De Dolares",
			"Jogos Da Vida",
			"Sete Noivas Para Sete Irmaos",
			"Lilo & Stitch (2002)",
			"Loucas Aventuras de Uma Familia Americana na Europa",
			"Amor Plus Size",
			"O Aluno Ducobu",
			"Jovem Hercules",
			"Esses Indomaveis Xerifes Quarentoes",
			"Anastacia, a Princesa Esquecida",
			"Ishi, o ultimo de sua Tribo",
			"A Praia dos Biquinis ",
			"Transformers",
			"Material Girls",
			"Nosso Amigo Frankestein",
			"Hercules E O Circulo De Fogo",
			"A Lenda da Flauta Magica",
			"Ali Baba e os 40 Ladroes ",
			"A Boneca Que Virou Gente",
			"Sapos",
			"Problemas Modernos",
			"Caçada Impiedosa",
			"Loucuras Em Hong Kong",
			"Quando o Amor Sorri ",
			"O Tesouro da Barba Azul",
			"Malevola",
			"Convençao Das Bruxas",
			"Jeannie e Ainda Um Genio",
			"Um Craque Animal 2 ",
			"Um Tira Da Pesada 2",
			"Meus Amigos Dinossauros",
			"O Tempo Certo De Amor",
			"Top Secret: Super-Confidencial",
			"Gloria e Lagrimas de um Comico",
			"O Inspetor",
			"O Juramennto do Zorro",
			"A Lenda do Tesouro Perdido: Livro dos Segredos",
			"Ping! ",
			"Mosqueteiros Do Mar",
			"Sempre Jovem ",
			"Incondicional ",
			"Agora e Sempre",
			"Sem Saida (1987)",
			"O Valente Treme-Treme",
			"Quero Ficar com Polly",
			"Alunos Muito Loucos",
			"Air America: Loucos Pelo Perigo",
			"Noiva Por Correspondencia",
			"Felpudo, O Cao Promotor",
			"Agnes De Deus",
			"aguias Em Alerta",
			"Roberto Carlos em Ritmo de Aventura",
			"Segurança de Shopping 2",
			"Superpai",
			"Galgameth",
			"Os Reis Da Praia",
			"Paulie: O Papagaio Bom De Papo",
			"Katie: Uma Garota Da Pesada",
			"Que Garota! Que Noite!",
			"Com O Dinheiro Dos Outros",
			"Tarde Demais Para Esquecer",
			"Carros",
			"Lembranças Perigosas",
			"Alice no Pais das Maravilhas ",
			"Caçadoras De Aventuras",
			"O Regresso Do Corcel Negro",
			"Companheiros",
			"Bronco Billy",
			"Os Monitores",
			"O Meninao",
			"O Incrivel Mr. Limpet",
			"As Garçonetes de Harvey",
			"Space Jam: O Jogo do Seculo",
			"De Repente Pai",
			"Digimon: O Filme",
			"Scooby-Doo E O Lobisomem",
			"Casamento Grego",
			"Um Tira E Meio",
			"E.T. O Extraterrestre",
			"Massacre No Bairro Japones",
			"Na Trilha Da Fama",
			"As Aventuras De Hajji Saba",
			"Amor a Primeira Mordida",
			"Percy Jackson e o Ladrao de Raios",
			"Sempre Ao Seu Lado",
			"E Se...Voce Tivesse Uma Segunda Chance?",
			"Ela e Demais",
			"O Incrivel Monstro Trapalhao",
			"Weekend em Palm Springs ",
			"Voce de Novo",
			"10 Coisas Que Eu Odeio Em Voce",
			"Xuxa E Os Trapalhoes Em O Misterio De Robin Hood",
			"Manequim: A Magia Do Amor",
			"Clonagem",
			"Os Herois Trapalhoes: Uma Aventura Na Selva",
			"Dois Supertiras Em Miami",
			"Diario de uma Paixao",
			"Jogo Da Vida",
			"Uma Viagem Inesperada",
			"Kart Racer: Alta Velocidade",
			"Heck: Ninguem Segura Esse Cachorro",
			"Atirando Para Matar",
			"Repo Man: A Onda Do Funk",
			"Um Golpe Das Arabias",
			"Aventura Sangrenta",
			"Fator Netuno",
			"A Venus de Bagda",
			"Mamae Saiu de Ferias",
			"Arthur, O Milionario Arruinado",
			"Um Tira Enrolado",
			"Aqueles Fantasticos Loucos Voadores",
			"O Seresteiro De Acapulco",
			"Uma Patricinha De Outro Mundo",
			"Xuxa E Os Duendes",
			"Quase Sem Destino",
			"Um Dia Muito Louco",
			"A Incrivel Mulher Que Encolheu",
			"Os Trapalhoes E O Rei Do Futebol",
			"O Grande Sucesso De Rock Hunter",
			"Primavera do Amor",
			"Amor Peso Pesado",
			"Uma Irma Em Minha Vida",
			"As Aventuras De Freddie",
			"Antes de Partir",
			"Meu Nome e Taylor, Drilbit Taylor",
			"Andre, Uma Foca Em Minha Casa",
			"Hospital De Herois",
			"A Primeira Transa De Jonathan",
			"Zoom: Academia De Super Herois",
			"Asterix & Obelix: Missao Cleopatra",
			"As Gemeas De Sorte",
			"Corrida Na Correnteza",
			"A Praia De Zuma",
			"Viagem ao Nucleo do Tempo",
			"De Volta a Lagoa Azul",
			"Motoqueiros Selvagens",
			"Principe Valent",
			"Voo Rasante",
			"Crazy People: Muito Loucos",
			"Os Filhos De Katie Elder",
			"O Falcao Dos Mares",
			"As Aventuras de Hajji Baba",
			"Felpudo, O Cao Enfeitiçado",
			"A Magia Das aguas",
			"Uma Familia Em Pe De Guerra",
			"Verao Muito Louco",
			"Indiana Jones E A ultima Cruzada",
			"Breakdance 2",
			"O Kennedy Esquecido",
			"Ferias no Havai",
			"A Guerra Dos Biscoitos ",
			"Um Ratinho Encrenqueiro",
			"Os Deuses Devem Estar Loucos 3: Loucuras Na China",
			"A Maquina Do Outro Mundo",
			"Em Busca De Uma Familia",
			"Um Tira Muito Especial",
			"Tron: Uma Odisseia Eletronica",
			"Alaska: Uma Aventura Inacreditavel",
			"Bailey, Um Cao Que Vale Milhoes",
			"Top Gang 2: A Missao",
			"Sempre Parceiro",
			"Infielmente Tua",
			"O Passaro Azul (1976)",
			"Os Meninos Voadores",
			"Adeus As Ilusoes",
			"O Calhambeque Magico",
			"Flores Do Po",
			"Scott da Antartica",
			"Flor do Pantano ",
			"Oito e Meio ",
			"Shiloh",
			"007 Contra O Homem Com A Pistola De Ouro",
			"O Tesouro do Barba Azul",
			"Sao Francisco de Assis",
			"Bonga, o Vagabundo",
			"Uma Aventura e Tanto ",
			"Tres Ladroes E Um Bebe",
			"Polo Norte ",
			"As Namoradas Do Papai",
			"Banze No Oeste",
			"Um Estranho Casal",
			"Teu Nome e Mulher",
			"Escala Em Toquio",
			"O Espiao do Nariz Frio",
			"Folias na Praia ",
			"Amor Ou Amizade",
			"As Aventuras De Papai Noel",
			"Passaporte Para O Perigo",
			"Robin e Marian",
			"O Professor Aloprado (1996)",
			"Loucuras De Verao",
			"A Dificil Arte De Amar",
			"O Pirata Sangrento",
			"Esposa de Mentirinha ",
			"Nunca Fui Beijada",
			"Lado A Lado",
			"Uma Historia De Luta",
			"Uma Aventura Selvagem",
			"O Milagre Da Montanha",
			"Principe Guerreiro 2",
			"Conan, O Destruidor",
			"Magnum: Nao Coma Neve No Havai",
			"Insubstituivel",
			"Professor Peso Pesado",
			"Tinker Bell: Uma Aventura No Mundo Das Fadas",
			"O Clube Das Babas",
			"Dupla Explosiva (1974)",
			"Figura Paterna",
			"Romeu e Julieta (2013) ",
			"A Menina E O Porquinho (2006)",
			"Madre Teresa: Em Nome dos Pobres de Deus",
			"Andre: Uma Foca Em Minha Casa",
			"Patrulha Beverly Hills",
			"Se O Marido Atender, Desligue",
			"Romance Inacabado",
			"Apesar dos Pesares ",
			"O ultimo Bravo",
			"Alguem La Em Cima Gosta De Mim",
			"Uma Cidade Contra o Xerife",
			"A Cançao do Havai ",
			"Gigantes de Aço",
			"De Volta Para Casa",
			"A Filha dos Trapalhoes",
			"Nosso Homem Em Bond Street",
			"Em Busca De Um Filho",
			"As Duas Faces de Zorro",
			"O Cristal Encantado",
			"Sem Medo De Viver (1969)",
			"Quem Era Aquela Mulher ",
			"Os Homens Sao de Marte...E e Pra La Que Eu Vou ",
			"As 7 Regras Do Amor",
			"Nossa Querida Baba 3: Uma Aventura No Paraiso",
			"Um Tira Em Apuros",
			"Double Dragon",
			"Em Busca De Confusao",
			"Darkman: Vingança Sem Rosto",
			"A Guerra intima Do Major Benson",
			"Um Conto Quase De Fadas",
			"Em Busca Do Vale Encantado",
			"Dumbo (1941)",
			"O Homem Da Lente Mortal",
			"Prece Para Um Pecador",
			"Areias Do Deserto",
			"Os Perigos de Pauline",
			"A Luta Por um Ideal",
			"Quase Casadas",
			"Vestida Para Casar",
			"O Filho Eterno",
			"O Amor Acontece",
			"3 Ninjas Contra Atacam",
			"Hercules E As Amazonas",
			"Crianças, A Mamae Saiu",
			"A Volta De Max Dugan",
			"O Passaro Azul ",
			"A Mansao Magica ",
			"Os Goonies ",
			"A Lenda do Tesouro Perdido",
			"Os Tres Mosqueteiros (1993)",
			"Entre o Amor e o Pecado",
			"Um Encontro Com Seu idolo!",
			"Cachorro Atomico",
			"As Patrcinhas De Beverly Hills",
			"Suplicio De Uma Vida",
			"Com Qual Dos Dois?",
			"A Morte e a Vida de Charlie",
			"Alvin e os Esquilos 3",
			"Mamae: Operaçao Balada",
			"Seis Dias, Sete Noites",
			"A Verdadeira Familia",
			"A Borboleta Azul",
			"Executivos Em Apuros",
			"Seu Desejo e Uma Ordem",
			"Armados E Perigosos",
			"Dennis, O Pimentinha",
			"Sequestro do Voo 285",
			"Coraçao De Leao: A Cruzada",
			"A Trilha Da Pantera Cor-De-Rosa",
			"O Terror Das Mulheres",
			"O Menino sue Queria ser Anjo",
			"O Retorno De Valentino",
			"Robocop, O Policial Do Futuro",
			"Apenas um Pequeno Incoveniente",
			"Vontade de Vencer ",
			"Castelos De Gelo",
			"O Mundo Fantastico De Oz",
			"Avalanche",
			"Uma Herança da Pesada",
			"Que Mundo Tentador",
			"Os Estagiarios",
			"Pequenos Espioes 2: A Ilha Dos Sonhos Perdidos",
			"Uma Cavaleira Em Camelot",
			"Branca De Neve E Os Tres Patetas",
			"Agente Secreto Contra Mr. X ",
			"X-Men 2 ",
			"Garfield 2",
			"H2O: Meninas Sereias",
			"O Detonador em Alta Voltagem",
			"Rocky V",
			"Porçao Do Amor Nº9",
			"A Guerra dos Calhambeques",
			"Os Tres Mosqueteiros (2011) ",
			"Bud: O Cao Amigo",
			"Um Homem Impossivel De Amar",
			"Aventuras do Tio Maneco",
			"Dois e Bom, Tres e Demais",
			"Bill & Ted: Dois Loucos no Tempo",
			"Uma Linda Mulher",
			"Meu Mestre. Minha Vida",
			"O Super Cerebro",
			"Audacia A Jato",
			"Os Desaparecidos ",
			"Os Parças 2",
			"Hotel Transilvania",
			"Zoom: Academia De Super-Herois",
			"Pequenos Guerreiros",
			"Uma Nova Tocaia",
			"Caçadores De Emoçao",
			"O Fabuloso Rocky Marciano",
			"Um Fugitivo Do Barulho",
			"Coraçao Leal",
			"O Aventureiro Do Pacifico",
			"A Autobiografia De Miss Jane Pitman",
			"O Leao Vesgo",
			"A Grande Farsa",
			"Destino lua",
			"Watusi, o Gigante Africano",
			"A Maquina de Fazer Biquinis ",
			"Marmaduke",
			"Evoluçao",
			"Quase Igual Aos Outros",
			"Os Batutinhas",
			"Mom And Dad: Uma Aventura No Espaço",
			"Marco Derradeiro",
			"Quem Esta Guardando Esta Erva?",
			"Fruto do Verao ",
			"Radio Rebel",
			"Aprendiz De Feiticeiro",
			"Projeto Secreto: Macacos",
			"Negocio Arriscado",
			"A ultima Viagem A Arca De Noe",
			"O Sequestro Do Voo 840: A Historia De Uli Derickson",
			"A Lenda Dos Anoes Magicos",
			"Cavalgada De Paixoes",
			"Tem um Homem na Cama de Mamae",
			"Duas de Mim",
			"e Para Sorte",
			"Meu Pai, Uma Liçao De Vida",
			"O Galante Vagabundo",
			"O Magico Inesquecivel",
			"Um Tira Da Pesada",
			"A Cor Do Amor: A Historia De Jacey",
			"A Ovelha Negra",
			"Kidco",
			"A Gaivota Negra",
			"Hitch: Conselheiro Amoroso",
			"Compramos um Zoologico",
			"X-Panze",
			"Um Sonho de Campeao",
			"Loucademia de Policia 7: Missao Moscou",
			"A ultima Ameaça",
			"Imitaçao Da Vida",
			"Tudo Que O Ceu Permite",
			"Encantada",
			"Homem De Ferro (2008)",
			"Duas Vidas",
			"A Casa Monstro",
			"Joey: Um Canguru Em Apuros",
			"D.A.R.Y.L.",
			"O Pirata Do Rei",
			"Corçaçoes Atormentados",
			"A Corrida do Seculo ",
			"Detetives do Predio Azul ",
			"As Ferias da Minha Vida ",
			"Que Garota, Que Noite",
			"Dominio Do Pavor",
			"O Quebra-Nozes (2010) ",
			"Coraçao De Dragao 2: Um Novo Começo",
			"Loucademia De Policia 5: Missao Miami Beach",
			"Rumos Desiguais",
			"O Espetaculo Nao Pode Parar",
			"As Tartarugas Ninja 2: O Segredo De Ooze",
			"Nada Em Comum",
			"A Viagem Infernal",
			"Clube Dos Cafajestes",
			"O Diario De Tati",
			"O Pestinha",
			"O Pestinha 3",
			"Crocodilo Dundee Em Hollywood",
			"O Atleta de Ouro",
			"Beleza Negra",
			"Mogambo",
			"A Feiticeira",
			"Robosapien: O Meu Melhor Amigo ",
			"Bebes Geniais",
			"Eu, Ela E A Outra",
			"Hotel Paradiso",
			"Destino as Nuvens ",
			"A Muralha da Esperança ",
			"A Bussola de Ouro",
			"O Amor e Cego",
			"Na Batida Do Coraçao",
			"Escola De Bruxas",
			"A Sorte Dos Irlandeses",
			"Doce Vingança",
			"Pelos Meus Direitos",
			"O Refem ",
			"Seefood: Um Peixe Fora Dagua",
			"O Rei Leao 2: O Reino De Simba ",
			"Sonhos No Gelo ",
			"Em Maus Lençois",
			"Voltando Para Casa",
			"Um Canguru Em Apuros",
			"O Homem Invisivel (1975)",
			"Coraçao De Leao",
			"Flechas ae Fogo",
			"As Aventuras do Ladrao de Bagda ",
			"Amor ao Acaso ",
			"Descendentes",
			"O Renascer De Uma Mulher",
			"A Filha Do Presidente",
			"O Fantasma De Canterville",
			"Hout: Dois Coraçoes, Uma So Batida",
			"A Ilha No Topo Do Mundo",
			"A Onda ",
			"O Palhaço que nao ri ",
			"A Inocencia Do Primeiro Amor",
			"De Volta as Ruas De Sao Francisco",
			"Embalos A Dois",
			"Golpe Sujo",
			"Nao Somos Anjos",
			"Salsa, O Filme Quente",
			"Uma Razao Para Vencer ",
			"Best Player: Guerreiros Virtuais",
			"Tinker Bell E O Tesouro Perdido ",
			"A Lenda Do Zorro",
			"Ciencia Travessa",
			"O Mascarado Contra os Piratas",
			"O Eterno Pretendente",
			"Stardust: O Misterio da Estrela",
			"Hannah Montana: O Filme",
			"Slappy E A Turma",
			"Katie, Uma Garota da Pesada",
			"Ensina-me A Querer",
			"A Familia Robinson",
			"Esta Pequena e Uma Parada",
			"Os Sobreviventes ",
			"Uma Folga Pra Mamae ",
			"Ate Que a Sorte Nos Separe 2 ",
			"Aprendendo A Viver",
			"De Caso Com A Mafia",
			"O Golpe Do Seculo",
			"Bonequinha de Luxo",
			"O Shaolin do Sertao",
			"Pesadelo Nas Alturas",
			"Perseguiçao Sem Limites",
			"Duas Babas Na Perfeitas",
			"Jornada Ao Centro Da Terra",
			"Brenda Starr ",
			"Força G ",
			"Bebe De Outubro",
			"Vovo...Zona 3: Tal Pai, Tal Filho",
			"Snow Buddies: Uma Aventura De Gelo ",
			"Surfistas Ninjas",
			"A Sombra De Um Passado",
			"Os Trapalhoes No Rabo Do Cometa",
			"O Fabuloso Ladrao De Bagda",
			"Bancando A Ama-Seca",
			"Tentaçao de Zanzibar ",
			"Natal Em Familia",
			"Air Bud: Uma Jogada Perfeita",
			"O Senhor Baba",
			"Tocaia",
			"Problemas Suburbanos",
			"Mensageiro Trapalhao ",
			"A Morte e Vida de Charlie ",
			"Uma Boa Açao",
			"Demolidor: O Homem Sem Medo",
			"Sinbad: Enlouquecendo Meu Guarda-Costas",
			"Os Herois Nao Tem Idade",
			"O Pequeno Principe",
			"Nova York: Terra De Ninguem",
			"Tres Em Um Sofa",
			"W.W. & Dixie ",
			"O Bicho Vai Pegar",
			"As Feras Da Musica",
			"Pega Ladrao",
			"Quando Paris Alucina",
			"Quando o Espetaculo Termina",
			"Alice Atraves do Espelho",
			"A Montanha Enfeitiçada (2009) ",
			"Aprendendo A Amar",
			"Super Xuxa Contra O Baixo Astral",
			"Os Trapalhoes Nas Minas Do Rei Salomao",
			"Popeye",
			"O Carrasco dos Tropicos",
			"Sexta-Feira Muito Louca",
			"A Familia Addams (1991)",
			"Os Viajantes Do Tempo",
			"O Principe Do Central Park",
			"A Princesa Encantada",
			"Um Verao Inesquecivel",
			"Os Dinossauros Voltaram",
			"As Ferias De Freddie",
			"Esperto Contra Sabido ",
			"O Zelador Animal",
			"Garfield: O Filme",
			"Maria: Filha Do Seu Filho",
			"O Dia Depois De Amanha",
			"Duro De Espiar",
			"Riquinho",
			"Resgate Impossivel",
			"Admiradora Secreta",
			"Encontro Fatal",
			"Splash, Uma Sereia Em Minha Vida",
			"Cortina Rasgada",
			"Talvez Algum dia",
			"Paris a Qualquer Preço ",
			"Pig: Uma Aventura Animal",
			"Pura Liberdade",
			"Maquina Mortifera 3",
			"Tal Pai. Tal Filho",
			"O Estopim Do Escandalo",
			"Tom Sawyer ",
			"Dragonball Evolution",
			"George, O Rei Da Floresta 2",
			"Supostamente Culpado",
			"Sobre Ontem a Noite",
			"Vinte Quilos De Confusao",
			"Pisando Na Bola",
			"3 Ninjas Em Apuros",
			"Inimigos Para Sempre",
			"Batman",
			"A Vida Secreta De Kate McCormick",
			"Descalços no Parque",
			"Carmen ",
			"Brooklin: Um Amor Sem Fronteiras ",
			"Eu Sou o Numero Quatro",
			"As Cronicas De Spiderwick",
			"Feita Por Encomenda ",
			"Flicka",
			"Scooby-Doo E A Escola Assombrada",
			"Brincou Com Fogo... Acabou Fisgado",
			"S.O.S. Submarino Nuclear",
			"Essa Pequena e uma Parada",
			"Os Croods",
			"Esqueceram De Mim 3",
			"D3: Nos Somos Os Campeoes",
			"Rapaz Solitario",
			"A Historia De Elza",
			"O Amor Tem Muitas Faces",
			"Amor a Toda Velocidade",
			"Operaçao Presente",
			"O Caminho Para El Dorado",
			"Os Deuses Devem Estar Loucos 2",
			"Entrando Numa Fria Maior Ainda Com a Familia",
			"Mudança De Habito",
			"Sem Sentido",
			"O Segredo De Monte Cristo",
			"De Repente, O Amor",
			"Mercador De Coraçoes",
			"A Princesa do Nilo",
			"Skylar: A Garota Destemida",
			"Que Droga De Vida",
			"O Potro Vermelho",
			"Maldosamente Ingenua",
			"A Flor do Pantano ",
			"O Otario e a Viarista",
			"Te Amarei para Sempre",
			"Annie (2014) ",
			"Recem-Casados",
			"Loucuras na Idade Media",
			"Rodas De Fogo",
			"A Fera Do Mar",
			"Os Incriveis Dobermans",
			"As 24 Horas de Le Mans",
			"A Paixao de uma Vida ",
			"Operaçao Cupido (1998)",
			"A Caixa De Pandora",
			"K-9: Detetive Particular",
			"Sob Suspeita",
			"O Campeao",
			"Dançando Nas Nuvens",
			"Seresteiro de Acapulco",
			"Assalto a um Castelo de Luxo ",
			"Uma Cançao e Um Beijo ",
			"Pai Por Acaso",
			"Hanni & Nanni 2",
			"As Aventuras De Pinocchio 2",
			"A Força Do Destino",
			"O Prisioneiro De Zenda",
			"Onde Estao As Crianças?",
			"Scooter: O Agente Secreto",
			"Rambo 3",
			"Cleopatra Jones E O Cassino De Ouro",
			"Fuga Alucinada",
			"Paz e a Nossa Tarefa ",
			"Uma Mae Para o Meu Bebe ",
			"A Cor Do Amor: A Historia Jacey",
			"A Intocavel",
			"Alguns Sim, Alguns Nao",
			"Um Dia De Sol No Natal",
			"Amelia Earhart",
			"A Creche do Papai ",
			"Fantasmas A Bordo",
			"Correndo Atras",
			"Yeti Em Nova York",
			"Ate Que Enfim e Sexta-Feira",
			"Um Anjo No Meu Bolso",
			"O cao Maravilhoso",
			"As Tres Espadas do Zorro ",
			"Depois da Terra",
			"Ela e O Cara",
			"Fievel: Um Conto Americano",
			"a Sombra De Uma Fraude",
			"Que Delicia de Guerra",
			"Papai Precisa Casar",
			"MIB: Homens de Preto 3",
			"Jenny Vai Casar ",
			"Intocaveis",
			"Pequenos Espioes",
			"O Cadillac Azul",
			"Amigos, Amigos... Negocios a Parte",
			"Labios De Fogo",
			"O Vencedor (1979)",
			"Marujos na Força Aerea",
			"A Historia de Tres Amores",
			"Quarta Dimensao",
			"Um Amor a Altura",
			"Escrito nas Estrelas (2001)",
			"Dificil Decisao",
			"Pequenos Grandes Astros 2 ",
			"3 Ninjas da Pesada",
			"Runaway, Fora De Controle",
			"Com o Amor no Coraçao",
			"O Rato na lua ",
			"Os Quatro Filhos de Açao",
			"No Assombroso Mundo da Lua ",
			"O Jovem Hercules",
			"Corrida Contra O Tempo",
			"O Gato De Botas",
			"A Morte Nos Sonhos",
			"Sangue Rebelde",
			"O Zorro Ataca de Novo",
			"O ultimo Mestre do Ar",
			"Par Perfeito",
			"Uma Garota Muito Especial",
			"Uma Escola Atrapalhada",
			"A Casa Do Espanto",
			"O Carro Desgovernado",
			"So Voce",
			"Surfe No Havai",
			"Skates: Na Pista Da Morte",
			"A Fuga Espetacular Do Ze Colmeia",
			"Os Anjos Tambem Comem Feijao",
			"O ultimo Aplauso",
			"Olha Quem Esta Falando Agora",
			"Policial Por Acaso",
			"Loucademia de Policia 3: De Volta ao Treinamento",
			"Meia-Noite e Um",
			"00Kid, Um Espiao Muito Especial",
			"Sonho De Verao",
			"Os Residentes",
			"Garotos Travessos",
			"A Noite Dos Amantes",
			"A Fera do Forte Bravo",
			"Showdown: Hora De Vencer",
			"Oscar: Minha Filha Quer Casar",
			"Mogli, O Menino Lobo (1942)",
			"A Flor Que Nao Morreu",
			"O Planeta dos Macacos (1968)",
			"Quando Sopra o Vento",
			"Agencia Patrimonial ",
			"Algemas de Cristal ",
			"O Mestre Do Disfarce",
			"Nao Tenho Troco",
			"Picardias Estudantis",
			"epoca Maluca",
			"Ambiçao Que Mata ",
			"Vice-Versa",
			"A Bela E A Fera (1987)",
			"Encontro A Tres",
			"So Por Uma Noite",
			"Os Seus, Os Meus, Os Nossos",
			"De Repente 30",
			"Minha Noiva De Mentira",
			"Pixel: A Garota Perfeita",
			"Whitney Brown ",
			"O Presente De Natal Perfeito ",
			"O Principe Do Egito",
			"Showdown: A Hora De Vencer",
			"Maya",
			"Corrida Para Stephanie",
			"Idas e Vindas do Amor",
			"Mentes Que Brilham",
			"A Fortaleza (1985)",
			"substituiçao temporaria pelo Festival de Ferias",
			"No Time dos Leoes",
			"O Foguete Errante ",
			"Querido John",
			"Ghost: Do Outro Lado da Vida",
			"Uma Noite No Museu",
			"Doze e Demais 2",
			"Karate Kid: A Hora Da Verdade",
			"Um Sonho De Natal",
			"Nasce uma Estrela ",
			"O Tirano da Fronteira ",
			"Labirinto: O Desafio Final ",
			"Jovens Bruxas",
			"Apertem Os Cintos... O Piloto Sumiu 2",
			"A Garota De Rosa Shocking",
			"Gelo Nas Alturas",
			"Destino a Lua",
			"Furia de Titas ",
			"Splash: Uma Sereia Em Minha Vida",
			"Comando Delta",
			"Fugindo Para Viver",
			"Detetives Em Açao",
			"Bonita E Perigosa",
			"Surf No Havai",
			"Cowboy Do Asfalto",
			"A Lenda De Sam agua Branca",
			"O Prisioneiro do Casbah",
			"Drama por um dia ",
			"Apenas Amigos",
			"Lagoa Azul: O Despertar",
			"Dias De Trovao",
			"Um Amigo Diferente 2: Dificil Jornada",
			"Principe Guerreiro",
			"Recem-Chegada",
			"O Anel Da Luz Eterna",
			"S.O.S Do Amor",
			"Romance Pirata",
			"O Incrivel Livro de Hipnotismo de Molly Moon ",
			"Vira-Lata (2007)",
			"Karate Kid (2010)",
			"Dr. Dolittle 4",
			"Super Controle Remoto",
			"O Guerreiro Americano 3",
			"Apertem os Cintos... O Piloto Sumiu!",
			"O Espiao de Nariz Frio",
			"Dr. Dolittle 2",
			"Bud 2: O Atleta De Ouro",
			"Luz De Cristal",
			"O Dragao E O Feiticeiro",
			"Banana Joe",
			"Inspetor Clouseau",
			"36 Horas ",
			"Ainda e uma Vez com Emoçao ",
			"Vovo... Zona 2 ",
			"Miss Simpatia 2: Armada e Poderosa",
			"Diario De Um Banana 2: Rodrick e O Cara",
			"A Grande Familia: O Filme",
			"Starstruck: Meu Namorado e Uma Superestrela",
			"Jogando Com A Vida",
			"Cuidado Com Meu Guarda-Costas",
			"Duas Paixoes",
			"somente para o RS ",
			"Rango",
			"O Sentido Da Vida",
			"Diferente",
			"Robocop: Uma Nova Missao",
			"A Testemunha",
			"Carrossel De Emoçoes",
			"O Barco das Ilusoes",
			"Natal dm Julho",
			"Ta Chovendo Hamburger",
			"Paixao de Aluguel",
			"Tarzan (1999)",
			"Atlantis: O Reino Perdido",
			"Um Tira Da Pesada 3",
			"Cinderela as Avessas",
			"Voando Para Casa",
			"Planos Secretos",
			"A Historia De Uma Vida",
			"Quem e Essa Garota",
			"Um Genio Entrou La Em Casa",
			"Meu Passado Me Condena 2",
			"Um Dia Especial",
			"O Pequeno Stuart Little 2",
			"Volta Por Cima",
			"Aeroporto 1980: O Concorde",
			"aguia De Aço 2",
			"Meu Coraçao Tem Dois Amores",
			"Tudo Azul com o Barba-Azul",
			"Simbad Contra o Olho de Tigre ",
			"Wendy Wu: A Garota Kung Fu",
			"Dois Cachorrinhos Milagrosos",
			"Hackers: Piratas de Computador",
			"F/X2: Ilusao Fatal",
			"De Volta ao Planeta dos Macacos",
			"O Fator Netuno: Odisseia Submarina",
			"Uma Familia De Fantasmas",
			"O Espanta Tubaroes",
			"Eu Aceito, Eles Nao",
			"Chuva De Milhoes",
			"Meu Tesouro e Voce",
			"A Bela Do Bas-Fond",
			"A Loteria do Amor",
			"Um Amor Peso Pesado",
			"Os Monkees Estao Soltos ",
			"O Incrivel Robo",
			"Sete Minutos No Paraiso",
			"Flor De Cacto",
			"Uma Mensagem de Esperança ",
			"Falando Grego",
			"Pocahontas: O Encontro De Dois Mundos",
			"Familia de Aluguel",
			"Um Adolescente Em Apuros",
			"Os Tres Mosqueteiros (1948)",
			"Sexta-Feira",
			"O Encanto de Viver ",
			"MIB: Homens de Preto 2",
			"Nas Profundezas Do Mar Sem Fim",
			"K-9: Um Policial Bom Pra Cachorro 2",
			"Busca Explosiva",
			"Quem Tudo Quer, Tudo Perde",
			"Em Busca De Aventura",
			"O Rei Do Laço",
			"O Nono Mandamento",
			"O Que Te Faz Mais Forte",
			"Acquaria ",
			"O Gato",
			"Mulher Nota 1000",
			"A Dupla Explosiva",
			"Um Cao De Mil Donos",
			"A Familia que Ninguem Queria",
			"Os Peregrinos",
			"Virada Radical",
			"Amor ao Primeiro Filho",
			"Lara Croft: Tomb Raider",
			"Nossa Vida com Caes ",
			"Batendo De Frente",
			"Hop: Rebelde Sem Pascoa ",
			"O Noivo da Minha Melhor Amiga",
			"Jimmy: Um Elo De Amor",
			"Chico Xavier",
			"Um Vampiro No Brooklyn",
			"Tres Amigos",
			"Esta e A Minha Chance",
			"Decisoes Extremas",
			"Zenon: A Garota Do Seculo 21",
			"Robin Hood: O Justiceiro",
			"Paternidade",
			"O Falcao Dourado",
			"Uma Vida De Louco",
			"A Farra Dos Malandros",
			"A Princesa e o Pirata",
			"O Homem Bicentenario",
			"Feitiço Da Lua",
			"As Ruas De Los Angeles",
			"Viva Um Pouquinho, Ame Um Pouquinho",
			"De Onde Eu Te Vejo",
			"Confissoes de uma Noiva",
			"Moondance Alexander: Superando Os Limites",
			"Simao: O Fantasma Trapalhao",
			"3 Trapalhoes Da Pesada",
			"A Historia Sem Fim",
			"Howard, O Super Heroi",
			"A Historia De Marva Collins",
			"A Viajante ",
			"Paginas Do Amor",
			"Pesos Pesados",
			"Gargantua",
			"Um Amigo Para O Natal",
			"O Beijo Da Despedida",
			"Xuxa Gemeas",
			"Uma Baba Quase Perfeita",
			"Querida, Estiquei O Bebe",
			"Torrentes De Paixao",
			"Com Amor no Coraçao",
			"Marley e Eu",
			"Os Feiticeiros De Waverly Place: O Filme",
			"Os Caçadores Da Arca Perdida",
			"Shredderman: Justiceiro Dos Nerds",
			"Nao Mexa Com Minha Filha",
			"O Amor Bate a Sua Porta ",
			"A Familia Addams 2",
			"Reaçao em Cadeia",
			"O Trapalhao Na Arca De Noe",
			"Sapos!",
			"O ultimo Detetive",
			"A Sorte No Lixo",
			"O Expresso De Chicago",
			"O Tempero Do Amor",
			"Kiss E O Fantasma Das Trevas",
			"Smokey",
			"Um Amor Verdadeiro (2014)",
			"Milagre Na Pista 2",
			"O Natal De Eloise",
			"Minha Amiga Ursinha",
			"Peter Pan (2003)",
			"O Corcunda De Notre Dame (1996)",
			"Mortal Kombat",
			"Inocencia Do Primeiro Amor",
			"O Escandalo Do Seculo",
			"A Maquina Do Amor",
			"Nossa Vida Com Papai",
			"Os Smurfs",
			"Clockstoppers: O Filme",
			"Em Boa Companhia",
			"I Yabba-Dabba Doo!",
			"Voo Cego",
			"Perdidos Na America",
			"Desastre No Rio Potomac",
			"As Cronicas De Narnia: O Leao, A Feiticeira E O Guarda Roupa ",
			"Goldenrod, o Campeao dos Rodeios ",
			"Chocante",
			"Paulie: O Papagaio Bom De Bico",
			"Um BlankMan: Um Super Heroi Muito Atrapalhado",
			"Aprontado em Alto Mar",
			"A Guerra dos Biquinis",
			"Justiceiros",
			"Sabes O Que Quero",
			"Festival de Ferias",
			"Astronauta por Acaso ",
			"Fuga do Planeta dos Macacos ",
			"Os Pinguins do Papai",
			"Arthur: O Milionario Irresistivel ",
			"Somos Marshall ",
			"Frozen: Uma Aventura Congelante",
			"El Dorado: Cidade De Ouro ",
			"Dragoes Para Sempre",
			"Confusoes No Natal",
			"Assassinato No Rio Grande",
			"O Principe Encantado",
			"O Romance De Murphy",
			"O Principe dos Piratas",
			"Arena dos Sonhos ",
			"O Negocio e Fofoca",
			"Vivendo Um Conto De Fadas",
			"Um Anjo Entre Nos",
			"Força De Emergencia",
			"Salty, A Adoravel Foquinha",
			"O Professor Aloprado (1963)",
			"Aladim e a Princesa de Bagda",
			"Sinfonia Prateada ",
			"Meu Monstro de Estimaçao",
			"O Fantasma",
			"Hercules Em Busca Do Reino Perdido",
			"O Vingador Do Futuro (1990)",
			"Kramer VS Kramer",
			"Star Wars Episodio 5: O Imperio Contra-Ataca",
			"Cinco Semanas Num Balao",
			"O Ceu e de Verdade",
			"Resgate Na Neve",
			"Fuga De Atlantida",
			"Supersnooper: Um Tira Genial",
			"Maratona Na TV",
			"Um Inferno na Neve ",
			"Daktari e Tarzan ",
			"Qualquer Gato Vira-Lata 2",
			"A Familia Buscape",
			"Karate Dog",
			"Mudança De Comportamento",
			"A Casa Magica",
			"Hook: A Volta Do Capitao Gancho",
			"Loucuras Em Plena Madrugada",
			"Rio de Sangue ",
			"Gato De Botas",
			"Karate Kid 4: A Nova Aventura",
			"Gus, Uma Mula Fora De Serie",
			"Agora Voce Nao Escapa",
			"Mulher de Fogo ",
			"A Vida Secreta da Nora ",
			"Roubo nas Alturas",
			"Shrek Terceiro",
			"Minha Mae e uma Peça: O Filme",
			"Bolt: Supercao",
			"Os Incriveis",
			"Motocross: A Aventura",
			"Meus Seis Amores",
			"Um Geek Encantador ",
			"Um Amor de Tesouro ",
			"Um Robo Em Curto-Circuito 2",
			"Os Herois Saem De Ferias",
			"Herança Nuclear",
			"A Arte do Amor",
			"George, O Rei Da Floresta (1997)",
			"Atlantis: O Retorno De Milo",
			"Carros Usados",
			"Amor a Primeira Vista",
			"O Castelo Invencivel",
			"Do Outro Lado da Ponte",
			"Procura Obsessiva",
			"Paraiso",
			"Dadiva De Amor",
			"Noite de Ano Novo ",
			"Mamae Saiu Com Um Vampiro",
			"A Familia Addams 2 (1993)",
			"Um Medico Irreverente",
			"Tres Coraçoes Solitarios",
			"O Brilho do Grand Canyon ",
			"A Vida Secreta de Nora ",
			"Querido Companheiro",
			"Os Porralokinhas",
			"So Resta A Esperança",
			"Enchente: Quem Salvara Nossos Filhos?",
			"Quatro Destinos",
			"Papai Pernilongo",
			"A Deliciosa Viuvinhaa",
			"Capitao Simbad",
			"Eles se Casam com as Morenas ",
			"Os Tres Desejos",
			"Um Principe Em Nova York",
			"Harriet, A Espia: Guerra Dos Blogs ",
			"Almondegas",
			"Mr. Billion",
			"O Sol Da Meia-Noite",
			"Cançoes e Confusoes",
			"Idilio na Selva",
			"Uma Familia Fuleira",
			"Aventureiro do Pacifico",
			"Independencia ou Morte ",
			"Imagine So",
			"Para Sempre Cinderella",
			"S.O.S Tem Um Louco Solto No Espaço",
			"O Homem de Oito Vidas",
			"Jovens no Coraçao",
			"Um Pestinha na Fazenda ",
			"A Maior Aventura de Tarzan ",
			"A Lagoa Azul",
			"Vida De Inseto",
			"Policia Desmontada",
			"Um Convidado Bem Trapalhao",
			"O Gaviao Do Mar",
			"Quatro Vidas de um Cachorro",
			"Homem-Aranha (2002)",
			"A Nova Onda Do Imperador 2: A Nova Onda Do Kronk",
			"A Dupla Dinamica",
			"De Passagem Pela Terra",
			"Esta Sobrando Uma Mulher",
			"Um Robo Em Curto-Circuito",
			"Policiais Trapalhoes",
			"Duelo nas Selvas",
			"O Grande Roubo ",
			"Caminhos Do Coraçao ",
			"Free Willy",
			"Animal (2001)",
			"Jesus",
			"Superman: O Filme",
			"Ninja, O Justiceiro",
			"O Enigma Da Piramide",
			"Ou Vai Ou Racha",
			"Flores de Aço (2012)",
			"Sabrina Na Australia",
			"Viajantes Do Futuro",
			"A Familia Addams",
			"Namorados Por Acaso",
			"Caleidscopio",
			"A Piramide de Cristal",
			"Sim Senhor ",
			"Os Irmaos Id & Ota",
			"Em Algum Lugar Do Passado",
			"Como Fisgar Um Marido",
			"Malabaristas Ilimitados ",
			"Meu Namorado e o Bicho",
			"Pequenos Grandes Astros",
			"George, O Rei Da Floresta",
			"O Caçador da Fronteira ",
			"Os Monstros Estao De Volta",
			"Um Maluco No Golfe",
			"Guerreiros De Virtude",
			"Viagem Insolita",
			"Stargate: Herdeiros Dos Deuses",
			"Fletch Vive",
			"A Rainha Tirana",
			"Pistoleiro Folgazao",
			"O Tempo e o Vento (2013) ",
			"Miss Simpatia",
			"Zamora",
			"O ultimo dos Bravos",
			"Lua Negra: O Super Carro",
			"O Brinquedo",
			"O Medalhao",
			"Bater ou Correr em Londres",
			"Sonhadora",
			"O ultimo Dia De Verao",
			"Congo",
			"A Rainha Do Nilo",
			"Cro em Familia",
			"Reencontro Mortal",
			"Academia De Combate",
			"Par Ou Impar",
			"Esther e o rei ",
			"Jogo de Amor em Las Vegas",
			"O Ceu Pode Esperar",
			"Simao, O Fantasma Trapalhao",
			"Crocodilo Dundee 2",
			"Lagrimas do ceu",
			"Tudo Por um Popstar",
			"Recem-Formada",
			"Viva O Rock N Roll",
			"somente para as afiliadas da Globo)",
			"As Mil Palavras",
			"Uma Familia em Apuros",
			"Sorte No Amor (2006)",
			"Batman Eternamente",
			"Dave, Presidente Por Um Dia",
			"American Ninja: Guerreiro Americano",
			"O Menino E O Leopardo",
			"Uma Aventura Inesquecivel",
			"Quando Floresce O Amor",
			"Demonios Da Pista",
			"Nome de Codigo, Cabeça de Dinamite ",
			"O Terno de 2 Bilhoes de Dolares",
			"Monte Carlo",
			"A Grande Fuga",
			"Rocky 3: O Desafio Supremo",
			"As Mil E Uma Noites",
			"A Escuridao Vencida ",
			"As Cronicas de Narnia: Principe Caspian",
			"Doce De Mae",
			"Agarra-me Se Puderes",
			"Começou Em Napoles",
			"Marujos Do Barulho",
			"Mar Raivoso ",
			"Scaramouche",
			"Marcha Nupcial ",
			"Climax ",
			"Homem-Aranha 2",
			"Conta Comigo",
			"A Condenada",
			"Tootsie",
			"As Aventuras De Robin Hood",
			"Ao Mestre com Carinho",
			"Nosso Amigo Frankenstein",
			"O Defensor",
			"Ela E Os Caras",
			"As Novas Aventuras De Riquinho",
			"Blankman: Um Super-Heroi Muito Atrapalhado",
			"A Passagem",
			"A Historia De Elza 2",
			"Tudo Pelo teu Amor",
			"Ozzie, Um Coala Do Barulho",
			"Eddie, O idolo Pop",
			"Papa Joao Paulo II ",
			"Os Nerds Saem De Ferias",
			"Casei-me Com Um Modelo",
			"Cantando na Chuva",
			"Toy Story 2",
			"Mentira Perfeita",
			"Escola De Rock",
			"Um Natal Milionario ",
			"Minhas Duas Mulheres",
			"Tarzan e o Grande Rio ",
			"Os Smurfs 2 ",
			"Marley & Eu 2: Filhote Encrenqueiro",
			"Pinocchio 3000",
			"Grease: Nos Tempos Da Brilhantina",
			"A Semente Do Diabo",
			"Streetdance: Dois Mundos, Um Sonho ",
			"Incontrolavel",
			"Shrek",
			"Spirit: O Corcel Indomavel",
			"Transformers (2007)",
			"Salve-me",
			"Demonios Na Pista",
			"Ama-me com Ternura ",
			"Um Rapaz de Outro Mundo ",
			"As Aventuras Dos 7 Anoes ",
			"Taina 2: A Aventura Continua",
			"Um indio Na Cidade",
			"Menino Maluquinho",
			"Com Merito",
			"Queda Livre",
			"Um Seculo Em 43 Minutos",
			"Felpudo, O Cachorro Promotor",
			"eramos Tao Felizes",
			"Noite Nupcial ",
			"Qualquer Gato Vira-Lata",
			"Os Caras de Pau em O Misterioso Roubo do Anel",
			"Como agua E Vinho",
			"So Lhe Restaram As Lagrimas",
			"Dizem que e Amor ",
			"Recanto de Paz ",
			"Como Nao Esquecer Essa Garota",
			"X-Men: O Filme ",
			"Correio Do Amor",
			"Uma Escola Muito Doida",
			"O Milagre Na Montanha: A Historia Da Familia Kincaid",
			"O Sargento Trapalhao",
			"Super Mario Bros",
			"Minha Mae e Uma Sereia",
			"Mago de Bagda",
			"Quem ri por ultimo",
			"Um Presente Para Toda Vida",
			"Um Pirado No Espaço",
			"Guerreiros De Fogo",
			"Barriga De Aluguel",
			"Condoman: O Homem Passaro",
			"Skeezer",
			"Sem Reservas",
			"Soul Surfer: Coragem de Viver",
			"O Bicho Vai Pegar 3",
			"Capitao Coragem",
			"Capitao Nemo E A Cidade Flutuante",
			"A Terra dos Handfords ",
			"Noites de Tormenta",
			"Menores Desacompanhados",
			"Pequenos Invasores",
			"Pequenos Segredos",
			"Zona Mortal",
			"Allan Quatermain E A Cidade Do Ouro Perdido",
			"Os Prazeres De Penelope",
			"Gidget ja e Adulta ",
			"Marte Precisa De Maes ",
			"Escola De Espioes",
			"A Vingança da Pantera-Cor-de-Rosa",
			"A Marca do Renegado",
			"Espangles",
			"O Guerreiro Didi E A Ninja Lili ",
			"Aladdin E Os 40 Ladroes",
			"Beethoven 4",
			"O ultimo Solteiro",
			"Meu Leal Companheiro",
			"Jesse",
			"Amor Fatal",
			"O que riu por ultimo",
			"Menino Selvagem ",
			"O Fada Do Dente 2",
			"Mergulho Em Uma Paixao",
			"Aventureiros De Fogo",
			"Senhor Baba",
			"Duro De Matar 2",
			"A Trama Dos Blakes",
			"Star Wars Episodio 6: O Retorno De Jedi",
			"As Aventuras De Huckleberry Finn",
			"A Mais Querida do Mundo",
			"Simplesmente Complicado",
			"Blankman: Um Super Heroi Muito Atrapalhado",
			"Meu Parceiro e Um Dinossauro",
			"Ladyhawke, O Feitiço De aquila",
			"Precisa-se De Um Homem",
			"A Virgem De Fatima",
			"O Magnifico",
			"Simbad, o Marujo Trapalhao",
			"Casamento Grego 2",
			"Curtindo A Vida Adoidado",
			"O Trapalhao E A Luz Azul",
			"Caçada Brutal",
			"Cachorro Divino",
			"O Enigma Do Outro Mundo",
			"Os Guardas Florestais",
			"Gente Grande 2",
			"Toy Story 3",
			"A Teoria de Tudo",
			"Viagem ao Centro da Terra: O Filme",
			"Malasartes e o Duelo com a Morte ",
			"Amigos Para Sempre",
			"Raposa De Fogo",
			"Sabrina",
			"Os Trapalhoes E O Magico De Oroz",
			"O ultimo Homem Inocente",
			"O Negrinho do Pastoreio",
			"Apos a Tempestade ",
			"O Livro do Amor ",
			"A Moedinha Da Sorte",
			"Tres Solteiroes E Uma Pequena Dama",
			"Os Flintstones: O Filme",
			"Tubarao 3",
			"Candleshoe: O Segredo Da Mansao",
			"Um Toque De Infidelidade",
			"Um Espirito Baixou Em Mim",
			"Ferias Frustradas",
			"Fuga para a luz do dia",
			"Gremlins ",
			"Salvem Minha Filha! ",
			"O Amor Pede Passagem",
			"Brigada 49",
			"Asterix & Obelix Contra Cesar",
			"Free Willy 2: A Aventura Continua",
			"Jaco E Jose",
			"O Setimo Filho",
			"Cartas Para Deus",
			"O Diario da Princesa 2",
			"Halloweentown 2: A Vingança De Kalabar",
			"Minha Montanha Encantada",
			"Feitiço Da Lua<",
			"A Carga Da Brigada Ligeira",
			"A Meia-Noite do Amor",
			"Inspetor Bugiganga",
			"Um Robo Em Curto Circuito",
			"O Irresistivel Forasteiro",
			"O Aprendiz de Feiticeiro",
			"Eu E Meu Guarda-Chuva",
			"A Nova Onda Do Imperador",
			"De Volta Para O Futuro",
			"A Vingança dos Nerds 3: A Nova Geraçao",
			"A Pequena Milionaria",
			"Um Conquistador Em Apuros",
			"Caçadores de Corais",
			"A Louca Aventura ",
			"Juntos Pelo Acaso",
			"Os 101 Dalmatas: O Filme",
			"Cara De Um Focinho De Outro",
			"Os Trapaceiros Da Loto",
			"Os Filhos Do Silencio",
			"Uma Janela Para O Ceu",
			"A Audacia a Jato ",
			"Carrascos do mar ",
			"O Arqueiro Misterioso ",
			"Tubarao",
			"Top Secret: Super Confidencial",
			"Transito Muito Louco",
			"Enrolados",
			"Trair E Coçar e So Começar ",
			"Os 102 Dalmatas",
			"Teenagers: As Apimentadas",
			"Loucademia de Policia 4: O Cidadao Se Defende",
			"Meus Dois Pais",
			"Mad Max 2: A Caçada Continua",
			"Hangar 18",
			"Candelabro Italiano",
			"Artimanhas do Amor",
			"Paraiso Havaiano ",
			"Uma Irma na Minha Vida",
			"Tentaçao Fatal",
			"Irmao Urso",
			"O Otario",
			"Um Hotel Bom Pra Cachorro ",
			"Voo Da Fantasia",
			"Top Dog: Uma Dupla Animal",
			"De Volta a Praia Dos Amores",
			"A Pequena Loja Dos Horrores",
			"Aladim e a Lampada Maravilhosa",
			"O Barco do Desespero ",
			"Matilda",
			"Revivendo O Amor",
			"Jesus: A Historia Do Nascimento",
			"Belas E Mimadas",
			"Fugindo da Morte",
			"Na Trilha Da Historia",
			"Legiao Do Deserto",
			"Lua-De-Mel Agitada",
			"Uma Escolha de Mae",
			"Flubber: Uma Invençao Desmiolada",
			"Pum! Emissao Impossivel",
			"A Madrasta",
			"Os Jetsons E Os Flintstones Se Encontram",
			"Howard, O Super-Heroi",
			"Devagar, Nao Corra",
			"Um Carro Eletrizante",
			"Patrulha De Beverly Hills",
			"O Grande Houdini",
			"Tudo Azul com o Barba Azul ",
			"Madagascar 3: Os Procurados",
			"As Aventuras De Max Keeble",
			"Laços Diabolicos",
			"Alcatraz: Fuga Impossivel",
			"A Maldiçao Da Pantera Cor-De-Rosa",
			"O Detetive Desastrado",
			"Herança De Um Valente",
			"Confusao no Hotel ",
			"X-Men: Primeira Classe ",
			"Bem-Vindo a Vida",
			"Nove Meses",
			"Dois Tiras Fora De Ordem",
			"O Instituto Da Vingança",
			"Hercules (1997)",
			"O Pestinha 2",
			"A Pequena Espia",
			"A Princesinha",
			"Criaturas",
			"O ultimo Ninja",
			"O Rei Do Circo",
			"Olhos Verdes",
			"Os Viuvos Tambem Sonham",
			"Venha Passar O Natal Conosco, Papai",
			"Natividade ",
			"Ta Todo Mundo Louco",
			"A Bruxa Do Bem",
			"A Onda Dos Sonhos",
			"Os Piratas de Tortuga",
			"As Aventuras de um Cachorro",
			"Escandalo Na Cidade",
			"Uma Vez So Nao Basta",
			"O Amor de Meus Sonhos",
			"Vencendo Desafios",
			"Garota Veneno",
			"Forças Do Destino",
			"O Julgamento Do Capitao Jensen",
			"A Familia Do Genio",
			"Degaus Para o Poder",
			"Eu, Robo",
			"Missao Quase Impossivel",
			"O Inferno De Dante",
			"Agora Voce Ve...",
			"Dois Pestinhas Em Apuros",
			"Mestres do Universo",
			"Aquele Gato Danado (1965)",
			"Hanky Panky, Uma Dupla Em Apuros",
			"O Pequeno Gigante",
			"Maos Talentosas: A Historia de Ben Carson",
			"Diario de um Banana 3: Dias de Cao",
			"Robocop 2",
			"Gente Muito Importante",
			"O Magico de Marte",
			"Fala Serio, Mae!",
			"Detona Ralph",
			"A Volta Do Guerreiro Americano",
			"A ultima Musica",
			"Mong E Loide",
			"Um Herdeiro Bobalhao",
			"Um Pedido De Natal",
			"Os Espertinhos",
			"Nos Bastidores da Vida",
			"As Loucuras de Mr. Jones ",
			"Como Treinar o Seu Dragao",
			"A Conselheira Amorosa",
			"Piratas do Caribe: O Bau da Morte ",
			"O Candidato (2013) ",
			"Pinoquio (1940) ",
			"High School Musical",
			"Ninguem Segura Esse Bebe",
			"Billy Madison: Um Herdeiro Bobalhao",
			"Scooby Doo E A Escola Assombrada",
			"Raizes Do Ceu",
			"Ainda uma vez, com Emoçao",
			"Um Bom Partido",
			"O Jogo Do Amor",
			"Um Beijo Inesquecivel ",
			"Procura-se Um Papai Noel Desesperadamente",
			"serie de mesmo nome, reeditada em formato de telefilme)",
			"Acertando As Contas Com Papai",
			"Um Heroi De Brinquedo",
			"Eles Fazem O Espetaculo",
			"Sonhos De Verao",
			"O Fantastico Capitao Nemo",
			"Inspetor Bugiganga 2",
			"Força Irresistivel",
			"Os Embalos De Sabado A Noite",
			"Digby, O Maior Cao Do Mundo",
			"Megamente",
			"O Vale dos Cavaleiros",
			"Liçao de Vida",
			"Air Bud Contra-Ataca",
			"e Pura Sorte",
			"Capitao America",
			"Liberdade nos Ceus",
			"A Coragem de Lassie",
			"The Good Doctor: O Bom Doutor ",
			"Footloose: Ritmo Contagiante",
			"Entre A Espada E A Rosa",
			"Quem Fica Com Os Amigos?",
			"Da-Me Tua Mao",
			"O Amor Da Trabalho ",
			"Flicka 2 ",
			"O Pai Da Noiva 2",
			"Minutemen: Os Viajantes Do Tempo",
			"Jogo Duplo",
			"Minha Filha",
			"Como Livrar-me Da Mamae",
			"Crianças Bem Amadas",
			"Ausencia De Malicia",
			"Os Marujos... na Força Aerea",
			"A 100 Passos de um Sonho",
			"Vovo...Zona 2",
			"Transformers: A Vingança Dos Derrotados",
			"Monstros VS Alienigenas",
			"Blizzard: Um Conto De Natal",
			"Quanto Mais Grana Melhor",
			"Assassinato Por Encomenda",
			"Trocando As Bolas",
			"Doce Lar",
			"Rocky 4",
			"Rambo 2: A Missao",
			"Cuidado Com As Gemeas",
			"Uma Tremenda Confusao",
			"O Imbativel",
			"Como Rechear um Biquini ",
			"Parada Inesperada",
			"Como Entrei Para A Faculdade",
			"Quem Encontra Um Amigo, Encontra Um Tesouro",
			"Minha Vida, Meus Amores",
			"Cheque Em Branco",
			"Dungeons & Dragons: A Aventura Começa Agora",
			"O Incrivel Elefante",
			"Historia De Elza 2",
			"Esqueceram De Mim",
			"A Volta Da Familia Sol, La, Si, Do",
			"S.O.B.: Nos Bastidores De Hollywood",
			"O Falcao Amigo",
			"Hataril",
			"Smoky ",
			"Minha Baba e Uma Vampira: O Filme",
			"Nossa Querida Baba: O Conto De Fadas Continua",
			"Uma Aventura Na America Selvagem",
			"Dr. Detroit E Suas Mulheres",
			"Bambi (1942) ",
			"O Reserva De Papai Noel",
			"Tentaçao Morena",
			"Somos Todos Iguais",
			"A Recruta Hollywood",
			"Maria: Uma Missao de Amor ",
			"As Aventuras De Pinocchio",
			"Os ultimos Duroes",
			"Uma Dupla Explosiva",
			"Um Tigre Domesticado",
			"Os Saltimbancos Trapalhoes: Rumo a Hollywood",
			"Hanni & Nanni",
			"Mulan (1998)",
			"Desafio Mortal (1996)",
			"As Aventuras De Rocky & Bullwinkle",
			"As Novas Aventuras Do Fusca",
			"O Milagre de Fatima",
			"A ultima Girafa ",
			"Solteiro as Soltas ",
			"Neve Pra Cachorro",
			"Bebes Em Açao",
			"Vovo…Zona 2",
			"Independence Day",
			"Mogli, O Menino Lobo 2 (2003)",
			"Tira Ou Ladrao",
			"O Genio no Asilo ",
			"O Diario da Princesa",
			"a Procura do Amor",
			"O Anjo Mora Ao Lado",
			"A Lady E O Lobo: O Bicho Ta Solto ",
			"O Grande Dragao Branco",
			"A Ilha Da Garganta Cortada",
			"A Contadora De Historias",
			"Os Rivais",
			"A Volta Do Monstro Do Pantano",
			"Do Jeito Que Voce e",
			"O Ceu e Testemunha",
			"Os Intrepidos Homens e Seus Calhambeques Maravilhosos",
			"Corina, uma Baba Perfeita",
			"Meu Nome e Taylor, Drillbit Taylor",
			"Mara e o Senhor do Fogo",
			"Os Trapalhoes E O Magicos De Oroz",
			"Uma Mensagem Para Minha Filha",
			"Anastasia, A Princesa Esquecida",
			"A Deusa Da Cidade Perdida",
			"Caminhos sem Volta",
			"Um Grande Garoto",
			"Shiloh 3",
			"Olha Quem Esta Falando Tambem",
			"aguia De Aço 3: Ases Do Ceu",
			"Qause Igual Aos Outros",
			"A Viagem Ao Grande Deserto",
			"Um Amor de Cachorro ",
			"Surpresas do Amor ",
			"Minhas Seis Esposas",
			"Atraidos Pelo Destino",
			"Te Pego La Fora",
			"O Menino De Ouro ",
			"A Joia Do Nilo",
			"As 7 Faces do Dr. Lao",
			"Artistas E Modelos",
			"So os Persistentes Sobrevivem",
			"Em Terreno Selvagem",
			"Os Aventureiros Do Bairro Perdido",
			"De Volta as Aulas",
			"Ernest: Um Trapalhao Na Cadeia",
			"O Rei Da Paquera",
			"As Novas Diabruras Do Fusca",
			"A Vingança Dos Nerds 3: Nova Geraçao",
			"O Caminho Dos Elefantes",
			"Os Nove Irmaos",
			"Um Heroi de Brinquedo 2 ",
			"Portal dos Guerreiros ",
			"Uma Liçao de Mae",
			"As Cronicas De Narnia: A Viagem Do Peregrino Da Alvorada",
			"Xuxa Em O Misterio de Feiurinha ",
			"O Sexto Homem",
			"Viva! A Baba Morreu",
			"Flicka 3 ",
			"Panico No Parque",
			"A Espia Que Veio Do Ceu",
			"Aeroporto 1975",
			"O Gaviao E A Flecha",
			"Rinoceronte",
			"No Limite do Espaço",
			"Evereste",
			"Dança Comigo?",
			"O Dragao Dourado",
			"Um Lugar Para Recomeçar ",
			"Muppets Do Espaço",
			"Class Act: Alunos Muito Loucos",
			"Corra Que A Policia Vem Ai 33 1/3: O Insulto Final",
			"Melodia Imortal",
			"Mundo Perdido",
			"Cia 2: Missao Alexa",
			"Esta Faltando Um De Nossos Dinossauros",
			"Competiçao De Destinos",
			"Ninja, A Maquina Assassina",
			"A Incrivel Jornada da Dra. Meg Laurel ",
			"Assassinato Nos Estados Unidos",
			"Safari 3000",
			"Filha Da Pecadora",
			"Volta, meu Amor",
			"Shiloh 2: Amigos Para Sempre",
			"Superman 4: Em Busca da Paz",
			"Manda-Chuva Em Beverly Hills",
			"Vivendo Livremente",
			"O Magico De Oz",
			"Desafio",
			"Super Escola de Herois",
			"Nem Que A Vaca Tussa",
			"Cocktail",
			"As Duas Faces Do Zorro",
			"Dominique",
			"Como Caes E Gatos",
			"Xuxa E Os Duendes 2: No Caminho Das Fadas",
			"Waterworld: O Segredo Das aguas",
			"Meu Papai e Noel 2",
			"Alta Tensao",
			"Debi & Loide: Dois Idiotas Em Apuros",
			"As Gemeas Da Sorte",
			"Os Incriveis Wallendas",
			"Capitao Blood",
			"O Diabo Disse nao",
			"O Diamante Mitera ",
			"Shrek Para Sempre",
			"Sem Licença Para Dirigir",
			"Aladdin (1986)",
			"reclassificado para 12 anos)",
			"Um Salto Para A Felicidade",
			"Morte, Amor e Traiçao",
			"Aventureiros do Fogo",
			"Loucademia De Esqui",
			"Ouro Maldito",
			"A Marca Do Zorro",
			"Quarteto Fantastico",
			"Um Principe Em Minha Vida 2: O Casamento Real",
			"Bingo: Esperto Pra Cachorro",
			"O Natal Maluco de Ernest",
			"Candleshoe, O Segredo Da Mansao",
			"Com 007 Viva E Deixe Morrer",
			"A Mae Solteira ",
			"O Papai Noel Trapalhao",
			"A Vingança De Gonzales",
			"As Aventuras De Ford Fairlane",
			"O Planeta Proibido",
			"Escravas da Babilonia",
			"Tres Palavrinhas ",
			"As Grandes Aventuras De Pee-Wee",
			"As Novas Viagens de Simbad",
			"As Trapaças do Falcao",
			"O Que de Verdade Importa",
			"Meu Primeiro Amor: Parte 2",
			"A Teoria Do Amor",
			"A Volta Ao Mundo Sob O Mar",
			"O Milagre ",
			"Karate Kid II: A Hora da Verdade Continua",
			"17 Outra Vez",
			"O Auto Da Compadecida",
			"Johnny, O Gangster",
			"Sumbarino Amarelo ",
			"Doze e Demais",
			"As Aventuras de Pi ",
			"O Homem Da Casa",
			"Academia De Genios",
			"A Vitoria Dos Bravos",
			"Superando o Passado ",
			"Um Tira No Jardim De Infancia",
			"Tres Trapalhoes Da Pesada",
			"Pare! Senao Mamae Atira",
			"Pelotao em Apuros",
			"Os Trapalhoes Na Serra Pelada",
			"Minha Noiva e Uma Extraterrestre",
			"As Violetas Sao Azuis",
			"Antes Do Inverno Chegar",
			"O Agente 711 Pede Socorro",
			"O Natal dos Coopers ",
			"A Cura (1995)",
			"Aquele Gato Danado",
			"O Menino Maluquinho",
			"A Sombra Ninja",
			"A Fantastica Fabrica De Chocolate (1971)",
			"Terra 2",
			"Do Destino Ninguem Foge",
			"Cartas Para Julieta",
			"Um Natal Brilhante",
			"Dr. Dolittle 5 ",
			"Viagem Ao Centro Da Terra",
			"Na Corte Do Rei Arthur",
			"A Lenda",
			"Veia De Campeao",
			"Blackout",
			"Sansao e Dalila",
			"Antonio e o Prefeito",
			"Entrando Numa Fria",
			"Uma Fada Em Nossas Vidas",
			"Ela e O Diabo",
			"Gremlins 2: A Nova Geraçao",
			"S.O.S Malibu",
			"A Delicia de Um Dilema",
			"As Loucuras de Dick e Jane ",
			"a Prova de Fogo",
			"De Volta Para O Futuro 3",
			"aguas Perigosas",
			"Um Roubo Quase Perfeito",
			"Ensina-me A Viver",
			"Sua Majestade, O Aventureiro",
			"apos o ultimo Video Show)",
			"A Melhor Festa do Ano ",
			"Coraçao De Campeao",
			"Lisbela E O Prisioneiro",
			"Mr. Magoo",
			"As Tartarugas Ninja 2: O Segredo Do Ooze",
			"Arena dos Sonhos 2 ",
			"2 Filhos de Francisco ",
			"Sorte No Amor",
			"Super-Heroi: O Filme",
			"A Casa Maluca",
			"Adoravel Sedutora",
			"O Segredo Do Meu Sucesso",
			"Ninguem Segura Essa Garota",
			"A Hora De Viver",
			"Ela ",
			"O Outro Eu",
			"Coraçao De Dragao",
			"SCI: Fighter",
			"Resgate Fatal",
			"O Estado de Interessante de Papai",
			"Querida, Encolhi as Crianças",
			"Barbie Como Rapunzel",
			"Casamento de Convivencia",
			"Tres Ninjas",
			"Batalhadores Heroicos",
			"Garotas e Mais Garotas",
			"Arthur E Os Minimoys ",
			"MIB: Homens De Preto",
			"A Malandrinha",
			"Drama Em Familia",
			"Senhor Do Sol",
			"A Prometida",
			"Piratas do Caribe: Navegando em aguas Misteriosas",
			"O Grande Dave",
			"Regresso A Halloweentown ",
			"Passe De Magica",
			"Entrega Especial",
			"Idilio Proibido",
			"Degraus Para O Poder",
			"A Lei da Terra ",
			"Licença Para Casar",
			"Um Amor Verdadeiro",
			"Como Treinar o Seu Dragao 2",
			"Herbie: Meu Fusca Turbinado",
			"Principe Guerreiro 3: O Olho Do Mal",
			"Investigaçao Perigosa",
			"Alunos Muitos Loucos",
			"O Manto Sagrado",
			"Cidade Sob O Mar",
			"Conan, O Barbaro (1982)",
			"Maldita Aventura",
			"Um dia em Nova York "};

}
